Dockerfile

When testing multiple deployment options, I found that node version and script issues.

ci(dockerfile): created a script to deploy

---

src/app.module.ts
src/auth/auth.controller.ts
src/auth/auth.module.ts
src/user/user.entity.ts
src/user/user.module.ts
src/user/user.service.ts

This PR adds processing on onboarding request for the logged in user, and adds the onboarding status to the user session to toggle the onboarding button in the UI.

feat: add onboarding endpoint and onboarding status to session endpoint

---

src/auth/auth.controller.ts
src/auth/dtos/supabase-auth-response.dto.ts
src/user/user.entity.ts

This PR returns the assigned insights role of the user with the session information

feat: add role for insights to session information endpoint

---

src/auth/auth.controller.ts
src/auth/dtos/supabase-auth-response.dto.ts
src/user/user.entity.ts
src/user/user.service.ts
supabase/migrations/20220510165555_add_users.sql

This PR:
- Adds the ability to select and update the waitlist status for an individual user
- Adds the `is_waitlisted` flag to the users migration script

feat: add ability to retrieve/update waitlist status for a user

---

README.md

Mentioned the need for the `.env` file for the project to run in the README.md, as well as the value of the `API_HOST` key for Windows users.
Fixes #41

docs: mentioned .env file

---

src/insight/insight.controller.ts
src/insight/insights.module.ts
src/insight/insights.service.ts
src/insight/user-insight.controller.ts

This PR
- Adds a new endpoint to retrieve a insight page using its id
- Fixes saving a new insight page after creation
- Moves original `insights.controller` to `user-insights.controller`

feat: add endpoint to retrieve insight page by id

---

src/insight/dtos/create-insight.dto.ts
src/insight/entities/insight-repo.entity.ts
src/insight/entities/insight.entity.ts
src/insight/insight-repo.service.ts
src/insight/insights.module.ts
src/insight/insights.service.ts
src/insight/user-insight.controller.ts

feat: add repos when creating an insight page

---

src/insight/dtos/create-insight.dto.ts
src/insight/user-insight.controller.ts

This PR:
- Adds the visibility flag when creating a new insight page

fix: add visibility flag to insight page creation

---

src/insight/insight-repo.service.ts
src/insight/insights.service.ts

fix: use save operation directly for insights, insight repos

---

src/insight/dtos/update-insight.dto.ts
src/insight/entities/insight-repo.entity.ts
src/insight/entities/insight.entity.ts
src/insight/insight-repo.service.ts
src/insight/insight.controller.ts
src/insight/insights.service.ts
src/insight/user-insight.controller.ts
supabase/migrations/20221028130800_add_insights.sql
supabase/migrations/20221028130900_add_insight_repos.sql

This PR:
- Adds endpoints to update an insight page and its associated repos
- Remove an insight page by soft deletion

feat: add endpoints to update/remove insight page

---

src/user/user.controller.ts
src/user/user.module.ts
src/user/user.service.ts

This PR:
- Adds the `/users/:username` endpoint to find a user by username

feat: add endpoint to find a user by username

---

src/auth/auth.controller.ts
src/user/user.entity.ts
supabase/migrations/20220510165555_add_users.sql

This PR:
- Adds additional fields to user record
Syncing information
- name (synced from GitHub)
- email  (synced from GitHub on connection, manual update after from insights)
- bio  (synced from GitHub)
- location  (synced from GitHub)
- twitter_username  (synced from GitHub)
- company  (synced from GitHub)
- display_local_time (Default `false`, manual update after from insights)
- timezone (Placeholder for future, manual update)

feat: add additional information to user record

---

src/auth/auth.controller.ts
src/user/dtos/update-user.dto.ts
src/user/user.entity.ts
src/user/user.service.ts

This PR:
- Adds the email to initial user data the first time the user is created
- Adds an endpoint to update the authenticated user profile

feat: add email to initial user data when session is used

---

src/auth/auth.controller.ts
src/user/dtos/update-user.dto.ts
src/user/user.entity.ts
src/user/user.service.ts
supabase/migrations/20220510165555_add_users.sql

This PR:
- Adds support for adding/updating interests to the user profile data
- Defaults to javascript
- Will be updated from the insights app

feat: add support for managing interests in the user profile

---

src/user/dtos/update-user.dto.ts
src/user/user.entity.ts
src/user/user.service.ts
supabase/migrations/20220510165555_add_users.sql

This PR:
- Adds remaining fields to user profile data
- Updates fields needed to update user profile

fix: add user profile fields to migrations, endpoints

---

src/auth/auth.controller.ts
src/auth/dtos/supabase-auth-response.dto.ts
src/user/dtos/update-user.dto.ts
src/user/user.entity.ts
src/user/user.service.ts

This PR:
- Enables the remaining user profile fields to be updated through the API

feat: add support for updating all user profile information

---

src/user/user-highlights.service.ts

This PR:
- Adds the title field to the data when creating a new highlight

fix: add title to new user highlight method

---

src/auth/auth.controller.ts
src/insight/dtos/create-insight.dto.ts
src/insight/entities/insight-repo.entity.ts
src/insight/insight-repo.service.ts
src/insight/user-insight.controller.ts
src/repo/dtos/repo-info.dto.ts
src/user-repo/user-repo.entity.ts
src/user-repo/user-repos.service.ts

feat: add support for capturing repo fullname on onboarding/insight repos

---

src/auth/auth.controller.ts
src/user/user.service.ts

This PR:
- Gets the email from the user data by default, and falls back to the session email if needed
- This is so that the current email for users is the one they've entered, which could be different from the signup email they used

fix: fetch user email as default with fallback to session email

---

src/auth/auth.controller.ts
src/user-repo/dtos/user-repos.dto.ts

fix: correct user_repos type mismatch

---

src/auth/auth.controller.ts
src/auth/dtos/user-onboarding.dto.ts
src/user/user.service.ts

This PR:
- Adjusts data needed for user completing onboarding process
- Sets `is_open_sauced_member` to `true` on new user account creation

feat: add new data when user is onboarding

---

src/user/dtos/create-user-highlight.dto.ts

This PR:
- Adds min/max length to the highlight validation

fix: add min/max length restriction to creating/updating a user highlight

---

src/auth/auth.controller.ts
src/auth/dtos/supabase-auth-response.dto.ts
src/user/dtos/update-user.dto.ts
src/user/user.entity.ts
src/user/user.service.ts
supabase/migrations/20220510165555_add_users.sql

This PR:
- Adds fields to the user profile for LinkedIn and GitHub sponsor links

feat: add user fields for LinkedIn, GitHub Sponsors

---

src/app.module.ts
src/highlight/dtos/highlight-options.dto.ts
src/highlight/entities/user-highlight-repo.entity.ts
src/highlight/highlight.controller.ts
src/highlight/highlight.module.ts
src/user/entities/user-highlight.entity.ts
src/user/user-highlights.service.ts
src/user/user.module.ts

This PR:
- Adds an endpoint to list all highlights by last updated date under `/highlights/list`
- This list can be filtered by an individual repo using the `repo` query param with the repo full_name (open-sauced/insights)
- Adds an endpoint to list all the repos by full_name that have highlights under `/highlights/repos/list`
Fixes https://github.com/open-sauced/ops-backend/issues/24

feat: add endpoints to list all highlights and repos

---

src/highlight/highlight.controller.ts
src/user/entities/user-highlight.entity.ts
src/user/user-highlights.service.ts
src/user/user.service.ts

This PR:
- Adds the user's full name to their highlight
- Backfills the user's full name to their user profile when created

feat: add user full name to highlights list data

---

src/app.module.ts
src/pull-requests/entities/pull-request.entity.ts
src/pull-requests/pull-request.controller.ts
src/pull-requests/pull-request.module.ts
src/pull-requests/pull-request.service.ts

This PR:
- Adds an endpoint to list pull requests

feat: add endpoint for pull requests

---

src/pull-requests/pull-request.service.ts
src/user/user.controller.ts
src/user/user.module.ts

This PR:
- Adds an `/users/:contributor/prs` endpoint to fetch pull requests for a contributor

feat: add endpoint to display pull requests for contributors

---

migrations/20230206150200_add_pull_requests.sql
src/common/dtos/filter-options.dto.ts
src/common/dtos/page-options.dto.ts
src/common/filters/repo-filter.module.ts
src/common/filters/repo-filter.service.ts
src/insight/dtos/insight-options.dto.ts
src/pull-requests/dtos/pull-request-page-options.dto.ts
src/pull-requests/pull-request.controller.ts
src/pull-requests/pull-request.module.ts
src/pull-requests/pull-request.service.ts
src/repo/dtos/repo-page-options.dto.ts

This PR:
- Adds a filter service to applying common filters for repositories
- Adds `/prs/search` endpoint to use filters for pull requests
- Updates indexes for pull requests migration

feat: add common filter service and add filtering support for pull requests

---

src/insight/insights.service.ts

This PR:
- Changes queryBuilder to use `take` instead of `limit` so all primary rows are returned before joins as recommended by TypeORM

fix: use take instead of limit for insight pages with join

---

src/pull-requests/entities/pull-request.entity.ts
src/pull-requests/pull-request.service.ts

feat: add repo full_name to pull request endpoints

---

src/contribution/contribution.module.ts
src/repo/dtos/repo-search-options.dto.ts
src/repo/repo.controller.ts
src/repo/repo.module.ts
src/repo/repo.service.ts
src/star/star.module.ts
src/stargaze/stargaze.module.ts
src/submit/submit.module.ts
src/vote/vote.module.ts

This PR:
- Adds a search endpoint for repos using filters without aggregating data

feat: add search endpoint for repos with filters

---

src/repo/entities/repo.entity.ts
src/repo/repo.service.ts

This PR:
- Adds insights for repos to the search endpoint for common stats about open/closed/merged/draft PRs
This provides

feat: add insights to repo search endpoint

---

src/insight/insight.controller.ts
src/insight/insights.service.ts
src/insight/user-insight.controller.ts

- Sorts insight pages by updated_at field
- Fixes equality checks for insight user_id

fix: sort insights by updated at, fix user_id checks

---

src/repo/repo.service.ts

- Only selects repo id when performing a subquery to get the count based on filters

fix: only use repos_id for count query when using filters

---

migrations/20230329093701_add_insight_team_members.sql
src/app.module.ts
src/insight/dtos/create-insight-member.dto.ts
src/insight/dtos/update-insight-member.dto.ts
src/insight/entities/insight-member.entity.ts
src/insight/insight-member.service.ts
src/insight/insights.module.ts
src/insight/insights.service.ts
src/insight/user-insight-member.controller.ts
src/insight/user-insight.controller.ts

- Adds API endpoints for managing team members and access for an insight page
Closes https://github.com/open-sauced/ops-backend/issues/3

feat: add endpoints for managing insight team members

---

src/insight/entities/insight.entity.ts
src/insight/insights.service.ts
src/user/user.entity.ts

Add owner information and establish relationship between insights and users
cc @brandonroberts and @OgDev-01 
- enforce relationships on github ids
- clean up entities

feat: add owner information and relationships to insight pages

---

src/repo/repo.service.ts

- Fixes bug with repos on insight pages not being displayed because they have not been updated within the date range

fix: only add range filter when not requesting specific repos

---

src/pull-requests/pull-request.service.ts
src/user/user.service.ts

Closes https://github.com/open-sauced/ops-backend/issues/44

fix: lowercase contributor value before using in queries

---

migrations/20230405125001_add_user_highlight_reactions.sql
src/user/dtos/create-user-highlight.dto.ts
src/user/entities/user-highlight.entity.ts
src/user/user-highlight.controller.ts
src/user/user-highlights.service.ts

- Adds `shipped_at` field to user highlights data
- Updates endpoints for managing a user highlight to accept this field
Closes https://github.com/open-sauced/ops-backend/issues/50

feat: add shipped_at field to user highlight data

---

LICENSE

fix: update license year

---

src/auth/auth.controller.ts
src/auth/dtos/supabase-auth-response.dto.ts
src/user/user.entity.ts
src/user/user.service.ts

- Adds unread notification count to user session information as `notification_count`

feat: add user notification count to session data

---

src/pull-requests/pull-request.service.ts
src/repo/repo.service.ts

Fixes the PR state query to match the data

fix: update queries for pull requests based on status

---

src/vote/vote.service.ts

Allows users to vote for a repo again after removing their previous vote.
Fixes #122

fix: vote a repo after removing old vote

---

src/app.module.ts
src/config/index.ts
src/config/openai.config.ts
src/pull-requests/dtos/create-pull-request-description.dto.ts
src/pull-requests/pull-request-description.controller.ts
src/pull-requests/pull-request-description.service.ts
src/pull-requests/pull-request.module.ts

- Adds an endpoint to generate a PR description from the provided inputs using OpenAI
- The endpoint requires authentication through OpenSauced
Closes #167

feat: add endpoint to generate pull request description

---

migrations/20230517151100_add_user_collaborations.sql
src/app.module.ts
src/user/dtos/create-user-collaboration.dto.ts
src/user/dtos/update-user-collaboration.dto.ts
src/user/entities/user-collaboration.entity.ts
src/user/user-collaboration.controller.ts
src/user/user-collaboration.service.ts
src/user/user.entity.ts
src/user/user.module.ts

- Adds migrations for creating user_collaborations table
- Adds endpoints for managing adding, updating, accepting, deleting user collaborations
Closes https://github.com/open-sauced/ops-backend/issues/35

feat: add endpoints for managing user collaborations

---

src/pull-requests/code-refactor-suggestion.controller.ts
src/pull-requests/code-refactor-suggestion.service.ts
src/pull-requests/dtos/create-code-refactor-suggestion.dto.ts
src/pull-requests/pull-request.module.ts

Adds an endpoint to generate code refactor suggestions.
https://github.com/open-sauced/ai/pull/90

feat: add endpoint to generate code refactor suggestions

---

.github/workflows/codeql-analysis.yml
.github/workflows/compliance.yml
.github/workflows/development.yml
.github/workflows/release.yml
.github/workflows/triage.yml
src/insight/dtos/create-insight.dto.ts
src/insight/entities/insight-repo.entity.ts
src/repo/dtos/repo-info.dto.ts
src/repo/entities/repo.entity.ts
src/user-repo/user-repo.entity.ts

Removing references to open-sauced/open-sauced due to the project being deprecated. I have already reached out to GitHub to redirect [this post](https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/) (our largest referred of traffic) to open-sauced/hot.
https://github.blog/2022-02-02-build-ci-cd-pipeline-github-actions-four-steps/
https://github.com/open-sauced/open-sauced/issues/1491

feat: remove open-sauced/open-sauced from ci yml

---

migrations/20230526151100_add_endorsements.sql
src/app.module.ts
src/config/api.config.ts
src/endorsement/dto/create-endorsement.dto.ts
src/endorsement/dto/update-endorsement.dto.ts
src/endorsement/endorsement-token.guard.ts
src/endorsement/endorsement.controller.ts
src/endorsement/endorsement.module.ts
src/endorsement/endorsement.service.ts
src/endorsement/entities/endorsement.entity.ts
src/user/user-endorsement.controller.ts
src/user/user.module.ts
tsconfig.json

- Adds endpoints for creating/listing endorsements
- Adds a token based route guard for creating endorsements

feat: add endpoints for managing endorsements

---

src/app.module.ts
src/contributor/contributor.controller.ts
src/contributor/contributor.module.ts
src/pull-requests/dtos/pull-request-contributor-options.dto.ts
src/pull-requests/dtos/pull-request-contributor.dto.ts
src/pull-requests/pull-request.service.ts

- Adds a new endpoint that retrieves all contributors based on filters and paginates them. The list contributors is unique for the search criteria provided.

feat: add endpoint for fetching contributors based on filters

---

src/app.module.ts
src/open-ai/open-ai.module.ts
src/open-ai/open-ai.service.ts
src/pull-requests/code-explanation.controller.ts
src/pull-requests/code-explanation.service.ts
src/pull-requests/code-refactor-suggestion.service.ts
src/pull-requests/code-test-suggestion.service.ts
src/pull-requests/code-test.suggestion.controller.ts
src/pull-requests/dtos/create-code-explanation.dto.ts
src/pull-requests/dtos/create-code-test-suggestion.dto.ts
src/pull-requests/pull-request-description.service.ts
src/pull-requests/pull-request.module.ts

This PR adds `explanation/generate`, `test/generate` endpoints to the PR service to generate code explanations and test generations as required by https://github.com/open-sauced/ai.
https://github.com/open-sauced/ai/issues/135, https://github.com/open-sauced/ai/issues/136

feat: generate code test, explanation on PR

---

src/user/user.service.ts

- Fixes a bug where an existing non-opensauced user connects their account.
Closes https://github.com/open-sauced/ops-backend/issues/52

fix: update existing user after they connect their account

---

src/repo/repo.service.ts

- Fixes queries for merged pull requests when displayed with repositories
Closes https://github.com/open-sauced/insights/issues/1281

fix: update query for merged pull requests for repositories

---

src/user/user-collaboration.controller.ts

- Adds a check to ensure the recipient of the collaboration request is accepting requests
- Adds a check to ensure the requester has the correct permissions to make collaboration requests

fix: add checks for requester and recipient for collaboration requests

---

src/stripe/stripe.service.ts

- This allows promo codes to be entered when initiating a checkout session with Stripe
Docs: https://stripe.com/docs/billing/subscriptions/coupons#add-promotion-codes-to-checkout
Related to https://github.com/open-sauced/ops-backend/issues/69

feat: enable promo codes with Stripe checkout

---

src/common/filters/repo-filter.service.ts
src/repo/repo.service.ts
src/user/user-recommendation.controller.ts
src/user/user.module.ts

- Adds an endpoint for retrieving user-interested based repo recommendations
The query pulls 3 repos from each user interest based on the following criteria:
- The repo has been updated within the last 30 days
- The repo has pull requests updated within the last 30 days
The returned repos are ordered by most recently updated.
Closes https://github.com/open-sauced/api/issues/184
Sample output
```
{
"javascript": [
{
"id": 89290483,
"size": 127528,
"issues": 591,
"stars": 4445,
"forks": 831,
"watchers": 4445,
"subscribers": 200,
"network": 831,
"is_fork": false,
"is_private": false,
"is_template": false,
"is_archived": false,
"is_disabled": false,
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"has_discussions": true,
"created_at": …
```

feat: add endpoint for repo recommendations

---

src/highlight/dtos/highlight-options.dto.ts
src/highlight/highlight.controller.ts
src/user/user-highlight.controller.ts
src/user/user-highlights.service.ts

This PR adds a new class `DbUserHighlightReactionResponse` to the `highlight-options.dto.ts` file, which extends the `DbUserHighlightReaction` class and picks only the necessary properties. 
In the `highlight.controller.ts` file, the `getAllHighlightReactions` method now returns an array of `DbUserHighlightReactionResponse` objects instead of `DbUserHighlightReaction` objects.
In the `user-highlights.service.ts` file, the `getAllHighlightReactions` method now returns an array of `DbUserHighlightReactionResponse` objects instead of `DbUserHighlightReaction` objects.
These changes improve the functionality and readability of the code.
Fixes #145 
Cannot upload a screenshot because I was not able to run the app. Just assumed that this …

fix: change swagger docs response for highlight reactions

---

src/user/user.entity.ts
src/user/user.service.ts

- Adds follower, following, recent pull requests and pull request velocity count to `/users/{username}` endpoint
- Hides followers/following count data synced from GitHub
Closes https://github.com/open-sauced/ops-backend/issues/75
Sample data
```json
{
"id": 42211,
"open_issues": 6,
"created_at": "2022-05-16T15:36:15.933Z",
"updated_at": "2023-07-01T00:26:58.382Z",
"first_opened_pr_at": "2022-05-16T15:36:15.933Z",
"first_pushed_commit_at": "2022-05-16T15:36:15.933Z",
"connected_at": "2023-06-16T19:27:00.041Z",
"node_id": "",
"avatar_url": "",
"gravatar_id": "",
"url": "https://brandonroberts.dev",
"is_private": false,
"is_open_sauced_member": true,
"is_onboarded": true,
"is_waitlisted": false,
"role": 50,
"bio": "Web developer, OSS maintainer, NgRx team, creator …
```

feat: add followers, following, recent pull requests counts to user info

---

src/common/services/api-services.module.ts
src/common/services/pager.service.ts
src/endorsement/endorsement.module.ts
src/endorsement/endorsement.service.ts
src/insight/insight-member.service.ts
src/user-repo/user-repos.service.ts
src/user/user-collaboration.service.ts
src/user/user-highlights.service.ts
src/user/user.module.ts

This PR includes the following updates:
* Creates ApiServicesModule in the common directory
* Creates PagerService that is responsible for applying `skip` and `limit` parameters to entities.
* Removes duplicated code

refactor: add pager service and drop duplicated code

---

src/highlight/highlight.controller.ts
src/user/entities/top-users.entity.ts
src/user/user.controller.ts
src/user/user.service.ts

[PR Description]
This pull request implements the "Top 10 Users" feature. It adds the necessary functionality to display a list of the top 10 users based on certain criteria. This feature will provide valuable insights into user activity and engagement. The implementation is complete and ready for review.
closes https://github.com/open-sauced/ops-backend/issues/76

feat: implement to 10 users feature

---

.github/workflows/development.yml

- Ensures the API builds in CI for pull requests

ci: add build workflow to CI

---

src/user/user-highlight.controller.ts

This PR fixes an issue where the id field was mistakenly included in the Swagger documentation for the highlights endpoint. The id field has been removed to ensure accurate and up-to-date documentation.
Fixes #174
Before
After

fix: remove id in swagger docs for highlights endpoint

---

src/user-repo/dtos/user-repos.dto.ts
src/vote/repo-vote.controller.ts
src/vote/vote.service.ts

This PR adds a new class `VotedRepoDto` to the `user-repos.dto.ts` file, which represents the data structure for checking if a user has voted for a repository. It includes a boolean property `voted` indicating whether the user has voted for the repo, and an optional property `data` of type `DbRepoToUserVotes` or `null`. 
In the `repo-vote.controller.ts` file, a new endpoint `GET /repos/:repoId/vote` has been added to check if the authenticated user has voted for a specific repository. The endpoint is protected with authentication and authorization guards. The response is of type `VotedRepoDto`.
The `vote.service.ts` file has been updated to include a new method `findOneByRepoId` which retrieves the vote for a specific repository by the authenticated user. If the vote exists and is not …

feat: add endpoint to check if authed user has voted the repo

---

.eslintrc.js
README.md
npm-shrinkwrap.json
package.json
src/contribution/contribution.service.spec.ts
src/contribution/repo-contributions.controller.spec.ts
tsconfig.json

In the previous #207 PR I forgot to configure `eslint` for `spec` files. This PR fixes it.
#207

refactor: setup unit tests

---

src/user/dtos/top-users.dto.ts
src/user/user.controller.ts
src/user/user.service.ts

closes https://github.com/open-sauced/ops-backend/issues/84

feat: add limit query params and pagination to top users endpoint

---

package.json
src/contributor/contributor-insights.controller.ts
src/pull-requests/dtos/pull-request-contributor-insights.dto.ts
src/pull-requests/pull-request.service.ts

- Adds a new endpoint for contributor insights to list all recent contributors in the last 30 days

feat: add endpoint for all recent contributors

---

migrations/20230405116001_add_user_highlights.sql
migrations/20230801105700_add_user_highlights_type.sql
src/user/dtos/create-user-highlight.dto.ts
src/user/entities/user-highlight.entity.ts

- Adds the `type` field to the `user_highlights` table
- Adds the type field to the database migrations
- Adds the type field to the user highlight entity
Closes https://github.com/open-sauced/api/issues/231
Sample output
```json
{
"id": 166,
"user_id": 37635083,
"url": "https://github.com/open-sauced/insights/pull/1429",
"title": "Improving the overall style ",
"highlight": "This commit adds width and max width for the \"created at\" element, improving the overall style and design. The changes aim to enhance the visual appearance and ensure better alignment.",
"type": "pull_request",
"pinned": false,
"featured": false,
"created_at": "2023-07-26T00:54:55.138Z",
"updated_at": "2023-07-26T00:54:55.138Z",
"shipped_at": "2023-07-26T05:54:55.082Z",
"name": "Nechiforel …
```

feat: add type field to user highlights table

---

.github/workflows/release.yml

This updates the release workflow to use the OpenSauced GitHub App for the semantic release job to provide correct access to push release commits to the necessary branches.

fix: update workflows to use GitHub app for semantic release versioning

---

src/user/user-highlights.service.ts

Allows accepting a "type" for highlights so we can extend highlights to blogs, issues etc.
When I add an issue from the frontend right now, it gets posted as a pull_request anyway.

feat: accept highlight type during highlight creation

---

src/app.module.ts
src/issues/dtos/create-issue-summary.dto.ts
src/issues/issue-summary.controller.ts
src/issues/issue-summary.module.ts
src/issues/issue-summary.service.ts
src/user/services/user.service.ts

This supports the development of https://github.com/open-sauced/insights/pull/1496 by adding the capability to summaries issues.
https://github.com/open-sauced/insights/pull/1496

feat: generate summary for an issue

---

src/user/entities/user-notification.entity.ts
src/user/user-notifcation.service.ts
src/user/user.entity.ts

See [comment below](https://github.com/open-sauced/api/pull/248#issuecomment-1673280598)
Fixes #247

feat: add source user info to the user notifications

---

src/app.module.ts
src/blogs/dtos/create-blog-summary.dto.ts
src/blogs/issue-summary.controller.ts
src/blogs/issue-summary.module.ts
src/blogs/issue-summary.service.ts

Auto summarise highlights with the type "blog".

feat: generate blog summaries

---

migrations/20230814160000_add_pull_requests_merged_by.sql
src/pull-requests/entities/pull-request.entity.ts

- Adds merge author to pull requests data

feat: add merge author to pull requests table

---

src/pizza/dtos/baked-repo.dto.ts
src/pizza/pizza-oven.controller.ts
src/pizza/pizza-oven.service.ts

This is a small PR fix for aligning the json `POST` body with what the pizza service expects. I.e., it primarily removes the required query parameter which didn't make alot of sense for the `/bake` endpoint.
Related to #218 
Now there is not required query parameter, just the necessary json request body which is more closely aligned with what gets sent to the pizza oven service.
Will need to land this in the beta / main environments to fully integrate the pizza service since the pizza-cli doesn't currently have query parameters for sending `bake` requests.

fix: Aligns pizza `POST` request with post JSON body

---

src/user/user-follow.service.ts
src/user/user-highlights.service.ts

- Fixes the query for follower notifications for highlights created. The query should fetch the users followers and send them a notification. Currently the query works in reverse and notifies the person they are following.

fix: fix query for sending notifications for created highlights

---

src/user/user-highlights.service.ts
src/user/user-notifcation.service.ts

- Fixes an issue where the username is added to the metadata instead of the id for a created highlight

fix: add highlight id to user notification metadata

---

src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user.entity.ts

- Adds the `is_maintainer` flag to the user information based on pull requests
Related to: https://github.com/open-sauced/ops-backend/issues/101

feat: add flag whether the user is a maintainer of repos

---

migrations/20230816130900_add_tagged_repos_to_highlights.sql
src/user/dtos/create-user-highlight.dto.ts
src/user/entities/user-highlight.entity.ts
src/user/user-highlights.service.ts

Should (?) add a tagged repos (array) column to the user-highlights table.
Kinda a shot in the dark since I didn't know how to test it.

feat: add tagged repos to user highlights

---

src/contributor/contributor-insights.controller.ts
src/pull-requests/pull-request.service.ts

- Updates DTO used to make request for new contributors
Closes https://github.com/open-sauced/api/issues/258
BEFORE:
AFTER:

fix: remove extra query parameters from new contributors endpoint

---

README.md
npm-shrinkwrap.json
package.json
src/main.ts
swagger.yaml

This creates / updates a Swagger yaml doc in the root project directory every time the server runs.
This doc should then be committed to source control and will be used to generate OpenAPI clients. For example, in the pizza-cli (https://github.com/open-sauced/pizza-cli/issues/28) this can be used to generate a Go client that can be used for canonical API calls.
Related to https://github.com/open-sauced/pizza-cli/issues/28
N/a

feat: Add Swagger YAML

---

src/auth/dtos/user-onboarding.dto.ts
src/endorsement/endorsement.controller.ts
src/main.ts
src/user/dtos/create-user-highlight.dto.ts
src/user/dtos/update-user-interests.dto.ts
src/user/entities/user-highlight.entity.ts
src/user/user.entity.ts
swagger.yaml

This PR fixes several problems with validation of our swagger doc through OpenAPI's code generation tooling:
```
Errors:
-attribute paths.'/v1/endorsements/user/{username}/created'(get).operationId is repeated
-attribute paths.'/v1/endorsements/user/{username}/received'(get).operationId is repeated
-attribute components.schemas.DbUser.default is not of type `object`
-attribute .servers.variables is not of type `object`
-attribute components.schemas.CreateUserHighlightDto.items is missing
-attribute components.schemas.DbUserHighlight.required is not of type `array`
-attribute components.schemas.UpdateUserProfileInterestsDto.items is missing
-attribute components.schemas.UserOnboardingDto.items is missing
-attribute components.schemas.PageDto.items is missing
```
Related to: …

fix: Swagger API doc fixes for code generation

---

src/user/user-collaboration.controller.spec.ts
src/user/user-collaboration.service.spec.ts

This PR adds unit tests for user collaboration service and controller
This PR is part of #215 issue
:smile:

test: add unit test for user-collaboration service and controller

---

src/user/dtos/top-users.dto.ts
src/user/services/user.service.ts
swagger.yaml

This PR filters out followed users from the top users list
Closes https://github.com/open-sauced/app/issues/1593

refactor: remove following users from top users when logged in user id is provided

---

src/main.ts

- Fixes an issue with getting access denied when writing the swagger file when starting up after the deployment

fix: update full path to swagger file for writing

---

nest-cli.generate-swagger.json
package.json
src/common/util/swagger.ts
src/generate-swagger.ts
src/main.ts
swagger.yaml

This removes generating the swagger spec within the actual app itself and instead offloads it to a `generate-swagger.ts` script that gets invoked via a different nest-js CLI config json file.
Related to https://github.com/open-sauced/api/pull/276
N/a
N/a

chore: Create a generate-swagger.ts script for generating swagger spec

---

migrations/20230828110600_add_org_ids_to_repos.sql
src/repo/entities/repo.entity.ts
src/user/user.entity.ts

- Adds organization_id to repos table and related entities
Related to: https://github.com/open-sauced/ops-backend/issues/96

feat: add field to associate repos to organizations

---

src/repo/entities/repo.entity.ts

- Fixes a typo bug introduced by https://github.com/open-sauced/api/pull/283

fix: update join column for user organization relationship

---

src/repo/repo.service.ts
src/user/user-recommendation.controller.ts
swagger.yaml

- Adds endpoint to return repo recommendations based on the users public organizations
- Data is sorted by stars, and most recently updated
- Only first 10 records are returned, but can be customized with `limit` query param
Related to: https://github.com/open-sauced/ops-backend/issues/96
Sample dev data output
```json
{
"data": [
{
"id": 511199000,
"size": 3352,
"issues": 38,
"stars": 1522,
"forks": 117,
"watchers": 1522,
"subscribers": 23,
"network": 117,
"is_fork": false,
"is_private": false,
"is_template": false,
"is_archived": false,
"is_disabled": false,
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"has_discussions": true,
"created_at": "2022-07-06T20:46:31.000Z",
"updated_at": "2023-08-29T20:56:09.503Z",
"pushed_at": …
```

feat: add endpoint for recommended repos based on user organizations

---

migrations/20230830083200_pizza_unique.sql

This ensures that `clone_url` and `commit_author_email` are unique in the pizza baking tables.
Related to https://github.com/open-sauced/pizza/pull/39
N/a

feat: make baked repos `clone_url` and `commit_author_email` unique

---

.env.example
README.md
dev/apply-migrations.sh

This includes:
- a script to apply all the migrations in the migrations directory
- an example .env file
Closes https://github.com/open-sauced/api/issues/226
N/a

feat: Script to apply all migrations and .env example

---

src/insight/insight-repo.service.ts
src/insight/insights.service.ts

This proof of concept is twofold:
- When an insights paged is fetched, it calls the pizza oven service for those repos, getting new commit data.
- When an insights page is created, it calls the pizza oven service for those repos, getting new commit data or backfill all author/repo commit data (since it may be a new repo we have not gotten commit data for)
This essentially flips the paradigm to only get new commit data when there is an active user request for it.
Curious to hear other's thoughts on this approach since it would be abit different then how we've backfilled data in the past.
Related to:
- https://github.com/open-sauced/etl.opensauced.pizza/issues/83
- https://github.com/open-sauced/etl.opensauced.pizza/issues/79
N/a

feat: Bake repos when new repos added to insights or fetched

---

src/insight/insights.module.ts

- Fixes runtime error with PizzaOvenService not being found in Insights Service, which caused a deployment failure.
Not sure why the build doesn't catch this ...

fix: import PizzaOvenModule to InsightsModule to fix runtime error

---

src/user/user-collaboration.controller.spec.ts
src/user/user-collaboration.controller.ts

Update UserCollaborationController to throw an UnauthorizedException with a custom error message when the requester's role is less than 50. This ensures that only authorized users can perform certain actions.
Fixes #292

fix: collaboration service return 401 when it should allow the action

---

src/user-lists/dtos/collaborators.dto.ts
src/user-lists/dtos/create-user-list.dto.ts
src/user-lists/dtos/filter-contributors.dto.ts
src/user-lists/entities/user-list-contributor.entity.ts
src/user-lists/entities/user-list.entity.ts
src/user-lists/user-list.controller.ts
src/user-lists/user-list.module.ts
src/user-lists/user-list.service.ts
swagger.yaml

- Creates the following crud routes:
- `/v1/lists/{id}/contributors` - [GET] Get paginated set of contributors in the list
- `/v1/lists/{id}/contributors` - [POST] Add new contributor to an existing list
- `/v1/lists/{id}/contributors` - [DELETE] Remove contributor from an existing list
- `/v1/lists/contributors` - [GET] Get paginated set of contributors to display when creating a list (w/filters)
- Sets `"integer"` type for swagger doc creation for user-list entities (this was a doubley nested array in the swagger doc before this change):
Related to https://github.com/open-sauced/api/pull/293
- [] 📜 README.md

feat: User-lists collaborators CRUD endpoints

---

migrations/20230911144301_add_commits_to_prs.sql
src/pull-requests/entities/pull-request.entity.ts

This adds a `commits` column to the `pull_requests` table in preparation for some of the list features coming in https://github.com/open-sauced/engineering/issues/123
This represents the number of commits associated with an individual PR.
More to come as this feature gets fleshed out. Next will be adding a backfill for this data to our ETL.
Related to https://github.com/open-sauced/engineering/issues/123
N/a
Will need to apply this migration to the beta/prod databases

feat: Add "commits" column to pull_requests table

---

.gitignore

Now the `dev/server.crt` and `dev/server.key` files are omitted from changes in git. I marked it as a code refactor, but it's really a chore, but the only chore is for cutting a release.
Fixes #307

chore: added dev certificate files to the git ignore list

---

src/user/services/user.service.ts

- Updates the SQL to lowercase the username when checking for maintainers
BEFORE:
Usernames with mixed case aren't getting the maintainer badge
AFTER:

fix: lowercase login to check for maintainers

---

swagger.yaml

chore: generate swagger.yml for 1.48.0 release

---

migrations/20230919111300_add_login_indexes.sql

- Adds additional indexes on the `pull_requests` table for `author_login` and `merged_by_login` on lowercase values.
- This speeds up queries where we lowercase the username for non-case-sensitive checks
- [] 🍕 Feature

fix: add migrations for pull requests indexes

---

src/pull-requests/dtos/pull-request-page-options.dto.ts
src/pull-requests/pull-request.service.ts
src/user-lists/user-list.service.ts

- Adds option to pull requests search to filter by contributors from a list
Output
```json
{
"data": [
{
"id": 1521956440,
"repo_id": 499330806,
"number": 315,
"state": "OPEN",
"draft": false,
"merged": false,
"mergeable": true,
"rebaseable": true,
"title": "chore: release 1.48.0",
"source_label": "",
"target_label": "",
"source_branch": "brandonroberts:beta",
"target_branch": "open-sauced:main",
"author_login": "brandonroberts",
"author_avatar": "https://avatars.githubusercontent.com/u/42211?u=32763fc85100fa45c5aa5d4bdddc4344e53d0173&v=4",
"assignee_login": "",
"assignee_avatar": "",
"created_at": "2023-09-20T01:40:25.000Z",
"closed_at": null,
"merged_at": null,
"merged_by_login": "",
"updated_at": "2023-09-20T20:44:24.000Z",
"last_updated_at": "2023-09-20T21:02:15.338Z",
"comments": 0, …
```

feat: add option search pull requests by list id

---

src/user-lists/user-list.controller.ts

Lists couldn't be deleted and would surface a 400 int parsing error:
This fix removes the `ParseIntPipe` which wasn't accepting the UUID string for the list.
cc @OgDev-01 
Related to various list work happening ing the App
N/a

fix: Enable proper string input of list IDs enabling delete

---

src/user-lists/user-list-stat.service.ts

The filters on `alum` and `new` contributors in the user list stats wasn't quite right: they needed to be flipped where for `alum` contributors, the `current_month_prs` is empty and for `new` contributors, the `previous_month_prs` is null.
Did abit of testing with this filter and I believe it makes more sense.
N/a - hotfix ontop of #320

fix: Updates the alum / new filters in user-lists-stats

---

src/pull-requests/pull-request.service.ts

This PR adds an implementation to ensure that the array of repoId is not empty. This helps make sure that the call to endpoints like `/v1/contributor/insights/` does not time out or take too long to return.
So I return an error with a message saying the repoid field can not be empty.
Fixes #306

fix: added fix to disallow empty repoids for `/v1/contributor/insights/`

---

src/auth/auth.controller.ts

- Instead of marking coupon as expired after one use, it can be used multiple times.

fix: add ability to apply coupon code more than once

---

migrations/20231005151900_add_user_list_contributor_username.sql
src/user-lists/dtos/create-user-list.dto.ts
src/user-lists/entities/user-list-contributor.entity.ts
src/user-lists/user-list.controller.ts
src/user-lists/user-list.service.ts

- Adds `username` to user_list_contributors table to capture non-OpenSauced users
- Left joins user_list_contributors on users to return non-OpenSauced users
- Adds db migrations
- Updates endpoint for adding list contributors
- [] 🍕 Feature

fix: add username when adding list contributors and left join users

---

src/user-lists/dtos/contributions-page.dto.ts
src/user-lists/dtos/contributions-pagemeta.dto.ts
src/user-lists/user-list-stat.service.ts

Adds two new datapoints for the "most active contributors" list endpoint
- `total_contributions` for each list contributor
- `all_contributions` within the metadata for all contributions counted across all entities
Example:
```json
{
"data": [
{
"commits": 261,
"prs_created": 39,
"total_contributions": 300
},
{
"commits": 25,
"prs_created": 14,
"total_contributions": 39
}
],
"meta": {
"page": 1,
"limit": 10,
"itemCount": 2,
"hasNextPage": false,
"allContributionsCount": 339
}
}
```
Closes #347 - cc @nickytonline let me know if this works for your needs!!! 🚢

feat: add "total_contributions" and "all_contributions" counts

---

src/user-lists/dtos/most-active-contributors.dto.ts
src/user-lists/user-list-stat.service.ts

Now you can order by `total_contributions` for the [/v1/lists/{id}/stats/most-active-contributors](https://beta.api.opensauced.pizza/#/User%20Lists%20service/getMostActiveContributors) endpoint.
Related to #351

fix: added order by total_contributions for user list stat service

---

.github/workflows/release.yml

- Adds generation of `swagger.yml` to release workflow

chore: add swagger generation to release workflow

---

src/user-lists/user-list.service.ts

Related to https://github.com/open-sauced/app/pull/1843
Doesn't allow for adding the same list contributor to the same list: checks if the contributor is already in the list and if they are, just returns that contributor in the service.
Closes: https://github.com/open-sauced/api/issues/358

feat: Don't allow adding the same list-contributors to a single list

---

src/user-lists/entities/contributions-projects.entity.ts
src/user-lists/user-list-stat.service.ts

This adds the `repo_id` field for the user-lists `stats/contributions-by-projects` endpoint.
Related to https://github.com/open-sauced/app/pull/1853

feat: add repo_id for contributions-by-project stat endpoint

---

src/user-lists/dtos/contributions-by-project.dto.ts
src/user-lists/user-list-stat.service.ts
src/user-lists/user-list-stats.controller.ts

This supports time range for contributions-by-project stats endpoint for the lists feature
Related to https://github.com/open-sauced/app/pull/1853

feat: Time range for contributions-by-project endpoint

---

src/user-lists/dtos/top-projects.dto.ts
src/user-lists/user-list-stat.service.ts
src/user-lists/user-list-stats.controller.ts

Related to and followup for:
- https://github.com/open-sauced/app/pull/1853
- https://github.com/open-sauced/api/pull/363
Adds a time range for the top-projects user-lists stats endpoint
- [x!] 🍕 Feature

feat: Time frame for top-projects user-lists stats endpoint

---

src/user-lists/dtos/filter-contributors.dto.ts
src/user-lists/user-list.service.ts

- Adds search by contributor login to list contributors endpoint

feat: add contributor search to list contributors

---

migrations/20231010140400_add_insights_featured.sql
src/auth/auth.controller.ts
src/auth/dtos/supabase-auth-response.dto.ts
src/insight/entities/insight.entity.ts
src/insight/insights.service.ts
src/user/services/user.service.ts
src/user/user.entity.ts

- Fetches featured insight pages for users who have not created any insight pages
- Adds insight count total to user session data
- Adds migration to insights table to setting featured insight pages
Related to: https://github.com/open-sauced/app/issues/1673

feat: add flag for featured insights, insights count to user session

---

src/user-lists/user-list-stats.controller.ts
src/user-lists/user-list.controller.ts

- Allow lists endpoints to be accessed without authentication for public list pages

fix: remove guards from lists stats endpoints

---

src/user-lists/user-list.service.ts

- Adds check if `userId` is provided before comparison
- Will revisit this check for non-auth requests for public/private checks

fix: update userId check for list

---

src/insight/insights.service.ts

- Fixes an issue where users that have created insight pages are shown featured insight pages
Only users who have never created an insight page should be shown featured insight pages
BEFORE:
AFTER:

fix: update query for showing featured insights

---

src/contribution/contribution.module.ts
src/contribution/contribution.service.spec.ts
src/contribution/contribution.service.ts
src/contribution/dtos/repo-user-contributions.dto.ts
src/contribution/entities/repo-user-contributions.entity.ts
src/contribution/repo-contributions.controller.ts

Allow for fetching contributions of sole contributors for a single repo given an owner/repo pair for a repos "full_name" and the login of the user in question.
Example:
```
'http://localhost:3003/v1/repos/open-sauced/api/jpmcb/contributions' \
```
returns
```
{
"commits": 38,
"prs_created": 19
}
```
Closes https://github.com/open-sauced/api/issues/380
I decided to add a different endpoint instead of tacking this onto `v1/contributors/search` since that endpoint is already pretty overloaded and there wasn't a great way to do this efficiently with all the filters already on that query.

feat: `v1/repos/:owner/:repo/:login/contributions`

---

src/user-lists/dtos/filter-contributors.dto.ts
src/user-lists/user-list.controller.ts
src/user-lists/user-list.service.ts

Enables multiple location and timezone selection when searching for list contributors.
Cc @OgDev-01 
Sending a request for both `Denver, Colorado` and `Alabama` returns expected results:
```sh
'http://localhost:3003/v1/lists/contributors?page=1&limit=10&location=Denver%2C%20Colorado&location=Alabama&pr_velocity=2' \
```
```json5
{
"data": [
{
"id": 42211,
"open_issues": 84,
"created_at": "2008-12-23T09:43:29.000Z",
"updated_at": "2023-09-25T20:24:38.969Z",
"first_opened_pr_at": "2012-10-06T08:35:52.000Z",
"first_pushed_commit_at": "2013-01-22T13:22:13.000Z",
"connected_at": "2023-06-16T20:27:00.041Z",
"node_id": "MDQ6VXNlcjQyMjEx",
"avatar_url": …
```

feat: Enable multi select for location and timezone

---

swagger.yaml

This is related to https://github.com/open-sauced/api/issues/317#issuecomment-1775905627 and fast-forwards the generated swagger to the most recent version of the api
I'll use this in the newest cut of the go-api client

fix: fast-forward swagger doc for most recent release

---

src/contribution/contribution.module.ts
src/contribution/contribution.service.spec.ts
src/contribution/contribution.service.ts
src/contribution/repo-contributions.controller.ts

This is a followup to https://github.com/open-sauced/api/pull/383
This adds a more granular way to get contributions for a repo from its contributors:
```
'http://localhost:3003/v1/repos/open-sauced/api/user-contributions' \
```
```json
[
{
"commits": 66,
"prs_created": 10,
"total_contributions": 76
},
{
"login": "Hack-Light",
"commits": 10,
"prs_created": 3,
"total_contributions": 13
},
{
"commits": 34,
"prs_created": 16,
"total_contributions": 50
},
{
"login": "nickytonline",
"commits": 1,
"prs_created": 1,
"total_contributions": 2
},
{
"login": "OgDev-01",
"commits": 9,
"prs_created": 2,
"total_contributions": 11
},
{
"login": "shavidze",
"commits": 2,
"prs_created": 2,
"total_contributions": 4
} …
```

feat: Granular contributions for individual repos

---

src/user/dtos/follow-many-users.dto.ts
src/user/services/user.service.ts
src/user/user-follow.controller.ts
src/user/user-follow.service.ts
swagger.yaml

Adds a `v1/{username}/follows` endpoint for following bulk users.
Query where neither user are already followed:
```sh
curl -X 'PUT' \
'http://localhost:3003/v1/users/{username}/follows' \
-H 'accept: */*' \
-H 'Authorization: Bearer <redacted>' \
-H 'Content-Type: application/json' \
-d '{
"usernames": [
"bdougie",
"brandonroberts"
]
}'
```
Result:
```json
{
"follows": [
{
"id": 64,
"user_id": 23109390,
"following_user_id": 5713670,
"created_at": "2023-07-13T04:03:30.544Z",
"updated_at": "2023-10-24T23:41:40.743Z",
"deleted_at": "2023-10-24T23:41:40.743Z"
},
{
"id": 121,
"user_id": 23109390,
"following_user_id": 42211,
"created_at": "2023-08-24T02:40:59.365Z",
"updated_at": "2023-10-24T23:41:33.896Z",
"deleted_at": "2023-10-24T23:41:33.896Z"
}
],
"errors": []
}
```
```sh
curl -X 'PUT' \ …
```

feat: Follow multiple users endpoints

---

src/user/user-organization.service.ts
src/user/user.controller.ts
src/user/user.module.ts

- Adds a `/v1/users/{username}/organizations` to display a list of public orgs for the user
Sample data
```json
{
"data": [
{
"id": 189,
"user_id": 42211,
"organization_id": 57568598,
"created_at": "2023-08-29T19:19:28.228Z",
"user": {
"id": 42211,
"open_issues": 91,
"created_at": "2008-12-23T08:43:29.000Z",
"updated_at": "2023-10-23T21:12:09.452Z",
"first_opened_pr_at": "2012-10-06T07:35:52.000Z",
"first_pushed_commit_at": "2013-01-22T12:22:13.000Z",
"connected_at": "2023-05-10T21:50:57.665Z",
"node_id": "MDQ6VXNlcjQyMjEx",
"avatar_url": "https://avatars.githubusercontent.com/u/42211?u=32763fc85100fa45c5aa5d4bdddc4344e53d0173&v=4",
"gravatar_id": "",
"url": "https://github.com/brandonroberts",
"is_private": false,
"is_open_sauced_member": true,
"is_onboarded": …
```

feat: add endpoint for public user organizations

---

src/contribution/repo-contributions.controller.ts
swagger.yaml

Hotfix ontop of https://github.com/open-sauced/api/pull/388
This also adds the org swagger bits from https://github.com/open-sauced/api/pull/393
Support for work in https://github.com/open-sauced/pizza-cli/issues/43
Need to release another go-api client for this to be consumed in the pizza CLI

fix: add "isArray = true" for contributors endpoint

---

src/auth/auth.controller.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts

Now you can delete a user from the system.
```bash
curl -X 'DELETE' \
'http://localhost:3001/v1/auth/profile' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Inp5NHZZbjM5MHlteTV0UmQiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjk4MzU1MzM0LCJpYXQiOjE2OTgzNTE3MzQsImlzcyI6Imh0dHBzOi8vZmNxcWt4d2xudG5ydGpmYmNpb3ouc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6Ijg1ZGY2OWY4LTFkZDUtNGVmNy05ODVjLTE4ZTkyMzRiZDNjNCIsImVtYWlsIjoibmlja0BpYW1kZXZlbG9wZXIuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJnaXRodWIiLCJwcm92aWRlcnMiOlsiZ2l0aHViIl19LCJ1c2VyX21ldGFkYXRhIjp7ImF2YXRhcl91cmwiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvODMzMjMxP3Y9NCIsImVtYWlsIjoibmlja0BuaWNreXQuY28iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiTmljayBUYXlsb3IiLCJ …
```

feat: users can be deleted from the system now

---

src/insight/entities/insight.entity.ts
src/user-lists/entities/user-list.entity.ts
src/user/entities/user-collaboration.entity.ts
src/user/entities/user-highlight.entity.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user.entity.ts
src/user/user.module.ts

TypeORM doesn't seem to play well with our use of foreign key relations during soft deletes. I tried a number of configurations proposed in https://github.com/typeorm/typeorm/issues/1460 and https://github.com/typeorm/typeorm/issues/5877 - I consistently got errors where the `user_id` was attempted to be updated to `NULL` which violated our foreign key constraints.
Instead, this manually gets the user's relations and manually soft deletes them.
Tested on my test user:
Correctly deletes user:
```
id         deleted_at                  login
137924913  2023-10-27 19:17:09.860376  not-linus-torvalds	
```
Correctly deletes highlight:
```
id   user_id    deleted_at
245  137924913  2023-10-27 14:57:26.229
```
Correctly deletes insight page:
```
id   user_id    deleted_at
307  137924913 …
```

feat: manually cascade soft deletes for users relations

---

.env.example
npm-shrinkwrap.json
package.json
src/app.module.ts
src/config/index.ts
src/config/tier.config.ts
src/tier/tier.module.ts
src/tier/tier.service.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user.module.ts

- Adds service to check/register users through tier.run/Stripe for feature flag support
- Adds new environment variables example config
- Updates test to mock TierService

feat: add tier.run service and check if user is registered

---

.env.example
src/config/tier.config.ts
src/tier/tier.service.ts

- Fixes issue where new users and people not enrolled get a pro plan instead of a free plan on beta

fix: enroll new users with a free tiered account

---

src/user-lists/user-list.controller.ts
src/user-lists/user-list.service.ts

Now the `/lists/${listId}/contributors` endpoint supports the query on `contributor` to search for contributors within the user list.
```
'http://localhost:3001/v1/lists/1286c011-ca5a-43e6-8dcd-fd50b129d144/contributors?page=1&limit=10&location=Denver%2C%20Colorado&location=Germany&contributor=bdougie&timezone=Mountain%20Standard%20Time&timezone=UTC&pr_velocity=2' \
```
example payload:
```json
{
"data": [
{
"id": "991e4fb1-9f8a-4f88-9851-2ebac643c6ec",
"user_id": 5713670,
"list_id": "1286c011-ca5a-43e6-8dcd-fd50b129d144",
"username": "",
"created_at": "2023-10-31T03:09:22.982Z",
"login": "bdougie"
},
{
"id": "08be31d7-e2e8-4625-9e94-4f3a72e7d44f",
"user_id": 20134767,
"list_id": "1286c011-ca5a-43e6-8dcd-fd50b129d144",
"username": "", …
```

fix: added missing search by contributor search term to /lists/${listId}/contributors

---

src/pull-requests/pull-request.service.ts
src/user/dtos/contributor-prs.dto.ts
src/user/user.controller.ts

- Adds a `rangeType` query param to the `/:username/prs` endpoint to allow all recent PRs to be listed instead of just the last 30 days
- Adds an enum to `rangeType` for `all` or `recent` PRs
Related to: https://github.com/open-sauced/engineering/issues/194

feat: add rangeType query param to contributor PRs endpoint

---

src/user-lists/user-list.service.ts

This prevents a full table scan on each contributor when filtering by only pr velocity.
Now, the following query takes about 3 seconds. Still not amazing since it has to scan all users, but at least the left join pervents a recursive scan on the pr table.
```sh
'http://localhost:3003/v1/lists/contributors?page=1&limit=10&pr_velocity=5' \
```
Other filters all seem to still work.
fixes #403
N/a

fix: Left join on prs for filtering on contributors

---

swagger.yaml

chore: update swagger.yml doc

---

migrations/20231201124300_add_lists_featured.sql
src/user-lists/entities/user-list.entity.ts
src/user-lists/user-list.controller.ts
src/user-lists/user-list.service.ts

- Adds `is_featured` field to `user_lists` table with DB migration
- Adds `/lists/featured` endpoint to retrieve featured lists

feat: add field and endpoint for featured user lists

---

migrations/20231205112300_add_user_campaign_start_date.sql
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user.entity.ts

- Adds `campaign_start_date` to users table
- Adds db migration
- Populates `campaign_start_date` for newly connected users
Related to: #https://github.com/open-sauced/engineering/issues/214

feat: add campaign_start_date field to users table

---

src/user-lists/user-list-stat.service.ts

The CTE was getting truncated by the provided `limit` (and since that chunk was not ordered by the total contributions, it was just getting a smaller subset of the total contributors list)
Partial fix for
- https://github.com/open-sauced/app/issues/2254
- https://github.com/open-sauced/app/issues/2092 
Using the following list connected to the prod database `b7f111c7-1bb5-4ebd-a6a3-8b0d3ca0d9c5` and a limit of 20, this now returns the right amount of contributors:
```
bschaatsbergen	81	17	98
jessehouwing	62	33	95
Fokko	52	33	85
DanielRieske	74	8	82
aatmmr	66	5	71
Yeseh	26	2	28
nbaars	24	1	25
JDarDagran	14	11	25
riezebosch	17	7	24
Calychas	18	1	19
pawel-big-lebowski	4	8	12
Geertvdc	11	1	12
sanderaernouts	5	3	8
tiborhercz	5	2	7
mobuchowski	3	4	7
rajbos	3	3	6
Nr18	3	3	6
mivano	3	1	4
jwills	2 …
```

fix: Most active contribs limit is now accurate

---

src/main.ts

fix: provide servers for Swagger page based on environment

---

migrations/20231213164135_insights_many_to_many.sql
migrations/20231213164135_workspaces.sql
src/app.module.ts
src/insight/entities/insight-member.entity.ts
src/insight/entities/insight.entity.ts
src/insight/insight-member.service.ts
src/insight/insight.controller.ts
src/insight/insights.service.ts
src/insight/user-insight.controller.ts
src/repo/entities/repo.entity.ts
src/user/services/user.service.ts
src/user/user.entity.ts
src/workspace/dtos/create-workspace.dto.ts
src/workspace/entities/workspace-insights.entity.ts
src/workspace/entities/workspace-member.entity.ts
src/workspace/entities/workspace-org.entity.ts
src/workspace/entities/workspace-repos.entity.ts
src/workspace/entities/workspace.entity.ts
src/workspace/workspace.controller.ts
src/workspace/workspace.module.ts
src/workspace/workspace.service.ts

Initial workspace feature:
- Database definitions for workspaces
- Includes changes to insights that makes them more agnostic (and able to be apart of workspaces as well)
- workspace get / create / delete
- Nest JS paradigms for workspaces

feat: Initial workspaces feature

---

src/pull-requests/pull-request.controller.ts
src/pull-requests/pull-request.module.ts
src/timescale/pull_request_github_events.service.ts
src/timescale/timescale.module.ts
src/user-lists/user-list.module.ts

This is a deep refactor that adds a v2 endpoint for `prs/search`.
This should capture all the functionality of the existing `prs/search` except for searching for spam PRs. There's some missing data in the timescale ingestion that we could look at building into the dataset
Related to:
- https://github.com/open-sauced/api/pull/442
- https://github.com/open-sauced/app/pull/2293
Run locally, connect to a timescale instance, make some queries via the swagger:

feat: V2 pr search using timescale data

---

src/timescale/pull_request_github_events.service.ts

There were some edge cases I missed with using lowercases and composite "IN" statements - this PR should fix those edge cases and work across complex filtering options provided by API consumers.
Hotfix and related to: #444 
Run db locally, run a complex query with multiple repos and multiple usernames. Note query works and includes all relevant information

fix: Correct usage of lowercases in composite "IN" statements

---

dev/Dockerfile.local-postgres
dev/apply-migrations.sh

This PR does a few things:
- Upgrades docker postgres version for local dev to pg 15
- Replace the innocuous password in the docker build with something alittle more obviously not a real password
- Use proper PGUSERNAME / PGDBNAME (especially since some linux systems expect "USERNAME" to be the system's username)
N/a
Startup the local docker postgres and apply migrations

feat: touchup some migration scripts

---

src/workspace/dtos/update-workspace.dto.ts
src/workspace/workspace.controller.ts
src/workspace/workspace.service.ts

- Adds a `patch/:id` for workspaces. This only updates metadata on the workspace. There will be separate endpoints for membership access.
- Adds workspace update DTOs
- Added a `canUserManageWorkspace` that checks a `accessRoles` array for the given user's role
- `leftJoinAndSelect` for workspace members when querying for workspaces
Related to: https://github.com/open-sauced/engineering/issues/215
Spin up API, can still query for workspaces (but now memberships are included):
```json5
{
"data": [
{
"id": "5ae72528-7195-471b-9cac-578abd509ddd",
"created_at": "2023-12-22T05:53:50.137Z",
"updated_at": "2023-12-22T06:30:14.593Z",
"name": "Woof woof",
"description": "Meow meow",
"members": [
{
"id": "dfa28e39-b3d7-4267-a61a-5f13fd220999",
"user_id": 23109390, …
```

feat: Add patch for workspaces

---

package.json

As we discussed in eng sync this morning, this is more or less ceremonious without any real changes. But as we push into more 2.0 API endpoints, we'll start removing old ones we don't need which are more breaking changes.
So this is the line in the sand. 
N/a
I assume that the releaser action will take care of this and get us the right versioning after this goes into beta - let me know if we want to implement deeper branching strategies here. I don't think we'll need that since we get versioning in the API code itself, we can just keep cutting stuff into the `V2` decorator and eventually cut out `V1` stuff.

feat: Upgrade NPM package to 2.0.0

---

src/workspace/workspace.controller.ts
src/workspace/workspace.service.ts

This PR is twofold:
- It uses the `feat!` conventional commit to force a major release via semantic release. This is a followup to #452 since that alone didn't force a 2.0 on the semantic release. I also didn't want to push an empty commit with `feat!` so this is tagging along on this workspaces fix:
- Deleting a workspace now checks that the authed user is a workspace owner before proceeding.
- I created the `findOneByIdAndUserId` helper function that gets a workspace based on id and user id. This is convenient since these are inherent 1 to 1 relationships with the workspace id and the user id.
Related to:
1. Created a workspace with two users (my real user as the owner and my test user as a viewer)
2. Attempted to delete the workspace as the viewer. Correctly get "unauthorized":

feat!: v2.0.0 (and workspace owners can delete)

---

src/app.module.ts
src/pull-requests/pull-request-review.controller.ts
src/pull-requests/pull-request.module.ts
src/timescale/entities/pull_request_review_github_event.ts
src/timescale/pull_request_review_github_events.service.ts
src/timescale/timescale.module.ts

- Adds the entity for pull request review events
- Adds a `/v2/prs/reviews/search` endpoint to search pull request review events based on filters
```json
{
"data": [
{
"event_id": 34372888259,
"pr_number": 2391,
"pr_state": "open",
"pr_is_draft": false,
"pr_is_merged": false,
"pr_mergeable_state": "",
"pr_is_rebaseable": false,
"pr_title": "feat: contributions treemap filtered by owners now",
"pr_head_label": "open-sauced:nickytonline/group-contributions-treemap-by-org",
"pr_base_label": "open-sauced:beta",
"pr_head_ref": "nickytonline/group-contributions-treemap-by-org",
"pr_base_ref": "beta",
"pr_author_login": "nickytonline",
"pr_created_at": "2023-12-21T15:15:58.000Z",
"pr_closed_at": "0001-01-01T00:00:00.000Z",
"pr_merged_at": "0001-01-01T00:00:00.000Z",
"pr_updated_at": …
```

feat: add endpoint for pull request reviews search

---

src/app.module.ts
src/histogram/dtos/stars.ts
src/histogram/histogram.controller.ts
src/histogram/histogram.module.ts
src/timescale/entities/watch_github_events_histogram.ts
src/timescale/timescale.module.ts
src/timescale/watch_github_events.service.ts

This introduces a `v2/histogram` service whose primary purpose is to generate histograms based on caller options. These histograms are generated [via Timescale `time_bucket` function queries](https://docs.timescale.com/use-timescale/latest/time-buckets/use-time-buckets/).
The first endpoint is the `v2/histogram/stars` endpoint which generates a histogram based on the given day range, repo name, and ordered by date asc or desc.
For example, given `open-sauced/app` in a 30 day range:
```json5
[
{
"bucket": "2023-12-31T00:00:00.000Z",
"star_count": 1
},
{
"bucket": "2023-12-29T00:00:00.000Z",
"star_count": 2
},
// redacted
{
"bucket": "2023-12-08T00:00:00.000Z",
"star_count": 1
},
{
"bucket": "2023-12-05T00:00:00.000Z",
"star_count": 1
}
]
```
Related to …

feat: Introduce `v2/histogram` service and `v2/histogram/stars` endpoint

---

src/histogram/dtos/base.ts
src/histogram/dtos/forks.ts
src/histogram/dtos/issue.ts
src/histogram/dtos/issue_comments.ts
src/histogram/dtos/pull_request.ts
src/histogram/dtos/pull_request_review.ts
src/histogram/dtos/pushes.ts
src/histogram/dtos/stars.ts
src/histogram/histogram.controller.ts
src/timescale/entities/fork_github_events_histogram.ts
src/timescale/entities/issue_comment_github_events_histogram.ts
src/timescale/entities/issue_github_events_histogram.ts
src/timescale/entities/pull_request_github_events_histogram.ts
src/timescale/entities/pull_request_review_github_events_histogram.ts
src/timescale/entities/push_github_events_histogram.ts
src/timescale/fork_github_events.service.ts
src/timescale/issue_comment_github_events.service.ts
src/timescale/issue_github_events.service.ts
src/timescale/pull_request_github_events.service.ts
src/timescale/pull_request_review_github_events.service.ts
src/timescale/push_github_events.service.ts
src/timescale/timescale.module.ts

Adds a `v2/histogram/pushes` endpoint for generated histograms
Also refactors the stars DTO to use a common shared DTO.
Example:
```sh
'http://localhost:3003/v2/histogram/commits?range=30&repo=open-sauced%2Fapp' \
```
```json5
[
{
"bucket": "2023-12-22T00:00:00.000Z",
"pushes_count": 24
},
{
"bucket": "2023-12-21T00:00:00.000Z",
"pushes_count": 37
},
// redacted
{
"bucket": "2023-12-05T00:00:00.000Z",
"pushes_count": 18
},
{
"bucket": "2023-12-04T00:00:00.000Z",
"pushes_count": 12
}
]
```
Related to #458 
N/a
1. Run locally with timescale secrets
2. Access the `v2/histogram/pushes` endpoint

feat: implements v2 histograms

---

src/workspace/common/memberAccess.ts
src/workspace/dtos/create-workspace.dto.ts
src/workspace/dtos/delete-workspace-member.dto.ts
src/workspace/dtos/update-workspace-members.dto.ts
src/workspace/workspace-members.controller.ts
src/workspace/workspace-members.service.ts
src/workspace/workspace.module.ts
src/workspace/workspace.service.ts

This PR implements 3 new endpoints (with a new service and new controller):
- `get` a workspaces members based on a given authenticated user
- `patch` a workspaces members based on a given authenticated user
- `delete` a workspaces members based on a given authenticated user
There is abit more logic in there too to prevent "orphaning" scenarios: a user cannot update their own role and cannot delete themselves. This should prevent owners from accidentally removing themselves or removing their access.
---
There are a few additional small changes:
- `canUserManageWorkspace` is in its own "common" directory which is more or less a convenience function for checking if a role for a workspace member can operate on a given workspace
- removes the unused `login` from the member dtos
Related to: …

feat: 🚂 1 - Workspace member management

---

src/workspace/dtos/delete-workspace-orgs.dto.ts
src/workspace/dtos/update-workspace-orgs.dto.ts
src/workspace/entities/workspace-org.entity.ts
src/workspace/workspace-orgs.controller.ts
src/workspace/workspace-orgs.service.ts
src/workspace/workspace.module.ts

This needs to merge _after_ #460 as it is a child PR ontop of those changes
---
- `get` workspace orgs:
```sh
'http://localhost:3003/v1/workspaces/orgs/b693750f-0c81-418a-b13c-b7d1518ca821?page=1&limit=10&range=30&prev_days_start_date=0' \
```
returns
```
{
"data": [
{
"id": "30a543dc-8031-4ced-8029-5e163ec21702",
"org_id": 57568598,
"workspace_id": "b693750f-0c81-418a-b13c-b7d1518ca821",
"created_at": "2024-01-05T01:18:39.060Z",
"updated_at": "2024-01-05T01:18:57.932Z",
"org": {
"id": 57568598,
"open_issues": 0,
"created_at": "2019-11-10T01:25:17.000Z",
"updated_at": "2022-12-24T05:46:21.000Z",
"first_opened_pr_at": "2019-11-10T01:25:17.000Z",
"first_pushed_commit_at": …
```

feat: 🚂 2 - Workspace orgs

---

src/workspace/dtos/delete-workspace-repos.dto.ts
src/workspace/dtos/update-workspace-repos.dto.ts
src/workspace/entities/workspace-repos.entity.ts
src/workspace/workspace-repos.controller.ts
src/workspace/workspace-repos.service.ts
src/workspace/workspace.module.ts

This needs to go in after https://github.com/open-sauced/api/pull/460 and https://github.com/open-sauced/api/pull/462
---
This, very similar to #462, implements workspace repo endpoints:
- `get` repos for a given workspace for the authenticated user
```sh
'http://localhost:3003/v1/workspaces/repos/b693750f-0c81-418a-b13c-b7d1518ca821?page=1&limit=10&range=30&prev_days_start_date=0' \
```
```json5
{
"data": [
{
"id": "9bca375d-8237-4525-a7cf-400b754346aa",
"repo_id": 499330806,
"workspace_id": "b693750f-0c81-418a-b13c-b7d1518ca821",
"created_at": "2024-01-05T06:06:38.902Z",
"updated_at": "2024-01-05T06:15:10.756Z",
"repo": {
"id": 499330806,
"size": 31073,
"issues": 41,
"stars": 37, …
```

feat: 🚂 3 - Workspace repos endpoints

---

migrations/20240103170955_workspaces.sql
src/app.module.ts
src/workspace/dtos/delete-workspace-contributors.dto.ts
src/workspace/dtos/update-workspace-contributors.dto.ts
src/workspace/entities/workspace-contributors.entity.ts
src/workspace/workspace-contributors.controller.ts
src/workspace/workspace-contributors.service.ts
src/workspace/workspace.module.ts

This needs to go in after https://github.com/open-sauced/api/pull/460 and https://github.com/open-sauced/api/pull/462 and #465 
---
This, very similar to https://github.com/open-sauced/api/pull/465, implements workspace contributor endpoints for a given workspace (i.e., the people that workspace is tracking)
- `get` contributors for a given workspace
```sh
'http://localhost:3003/v1/workspaces/contributors/b693750f-0c81-418a-b13c-b7d1518ca821?page=1&limit=10&range=30&prev_days_start_date=0' \
```
This returns the given workspace
- `patch` contributors for a given workspace
```sh
curl -X 'PATCH' \
'http://localhost:3003/v1/workspaces/contributors/b693750f-0c81-418a-b13c-b7d1518ca821' \
-H 'accept: …
```

feat: 🚂 4 - Workspace contributors

---

src/user-lists/user-list.service.ts

This PR fixes the pagination logic for lists contributors highlights and tagged repos
fixes #468

fix: now highlights pagination are accurate

---

src/user-lists/user-list.service.ts

This PR fixes an issue introduced in https://github.com/open-sauced/api/pull/469 that causes the `/list/${list_id}/contributors/highlights/tagged_repos` endpoint to return and empty data always. Didn’t create a ticket since this is still in beta.

fix: bug with highlight repos returning empty

---

README.md

This PR add extra steps to clarify the project setup, since we follow the steps and highlights, I thought we should highlight the navigations as well.
Closes https://github.com/open-sauced/api/issues/447

docs: clarify the local setup

---

src/user-lists/user-list-events-stats.service.ts
src/user-lists/user-list-stats.controller.ts
src/user-lists/user-list.module.ts

- Adds a v2 endpoint for `/lists/{listId}/stats/most-active-contributors`
Closes #321 
Includes new output for prs_reviewed, issues_created, commit_comments, issue_comments, pr_review_comments, and total comments based on those.
```json
{
"data": [
{
"login": "nickytonline",
"commits": 145,
"prs_created": 24,
"prs_reviewed": 129,
"issues_created": 33,
"commit_comments": 0,
"issue_comments": 127,
"pr_review_comments": 53,
"comments": 180,
"total_contributions": 511
},
{
"login": "ccordoba12",
"commits": 94,
"prs_created": 7,
"prs_reviewed": 44,
"issues_created": 2,
"commit_comments": 0,
"issue_comments": 81,
"pr_review_comments": 21,
"comments": 102,
"total_contributions": 249
},
{
"login": "urish",
"commits": 71,
"prs_created": 3,
"prs_reviewed": 0,
"issues_created": 0,
"commit_comments": …
```

feat: add v2 endpoint for user lists most-active-contributors stats

---

.env.example
src/app.module.ts
src/config/hacktoberfest.config.ts
src/config/index.ts
src/pull-requests/pull-request-insights.service.ts
src/pull-requests/pull-request.service.ts
src/repo/repo.service.ts
src/timescale/pull_request_github_events.service.ts

This PR removes hacktoberfest filtering and all references to hacktoberfest within the API.
Related to #478 - breaking changes in the API for v2 so this is landing on `alpha`
N/a
All routes should still work as expected. Primarily:
- `v1/repos/search`
- `v1/prs/search`
- `v2/prs/search`
👍🏼

chore: v2 API 👨🏻‍🍳 - Remove hacktoberfest filtering and all references to hacktoberfest

---

src/common/decorators/deprecated.decorator.ts
src/generate-swagger.ts
src/histogram/dtos/base.ts
src/histogram/histogram.controller.ts
src/main.ts
src/pull-requests/pull-request-insights.service.ts
src/pull-requests/pull-request-review.controller.ts
src/pull-requests/pull-request.controller.ts
src/pull-requests/pull-request.service.ts
src/repo/repo.module.ts
src/repo/repo.service.ts
src/timescale/entities/pull_request_github_events_histogram.ts
src/timescale/pull_request_github_events.service.ts
src/timescale/timescale.module.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user.controller.ts

This is a massive overhaul of existing endpoints and integrates
This will need to be closely coordinated with a frontend / consumer PR that takes advantage of the v2 endpoints.
Related to:

feat:  v2 API 👨🏻‍🍳 - add all v2 endpoints and implement timescale integration

---

src/generate-swagger.ts
src/user-lists/entities/contributions-timeframe.entity.ts
src/user-lists/user-list-events-stats.service.ts
src/user-lists/user-list-stat.service.ts
src/user-lists/user-list-stats.controller.ts

This implements a much faster v2 contributor evolution histogram:
---
- Updates the missing v2 for swagger generation
- Updates the `DbContributionStatTimeframe` type to have all the new data points
- Implements a `findContributorsByType` helper function which returns usernames for the given "type" (churn, new, alum, etc.) This was _much_ easier than trying to implement this across a `time_bucket` which I'm not sure is possible. Or at least, it'd be very gross to try to do without a helper query/function
- Implements `findContributionsInTimeFrame` which uses `UNION ALL` across many of the events tables given the usernames
Example `v2/lists/{id}/stats/contributions-evolution-by-type`:
```json5
[
{
"bucket": "2024-01-08T00:00:00.000Z",
"commits": 19,
"prs_created": 1,
"prs_reviewed": 17, …
```

feat: v2 API 👨🏻‍🍳 - V2 contrib evolution

---

src/common/filters/repo-filter.service.ts
src/insight/dtos/insight-options.dto.ts
src/repo/dtos/repo-page-options.dto.ts

- Adds `top-repos` filter to repo filter service to go with UI change in https://github.com/open-sauced/app/pull/2460

fix: add top repos filter to repo filter service

---

src/user-lists/user-list-events-stats.service.ts
src/user-lists/user-list-stat.service.ts
src/user-lists/user-list-stats.controller.ts
src/user-lists/user-list.module.ts

Updates contribs evolution by contribs type to use timescale data.
Example `/v2/lists/{id}/stats/contributions-evolution-by-contributor-type]`:
```json5
[
{
"bucket": "2024-01-16T00:00:00.000Z",
"all": 44,
"active": 60,
"new": 2,
"alumni": 0
},
{
"bucket": "2024-01-15T00:00:00.000Z",
"all": 23,
"active": 47,
"new": 0,
"alumni": 0
},
// ... redacted
{
"bucket": "2023-12-19T00:00:00.000Z",
"all": 77,
"active": 116,
"new": 3,
"alumni": 0
},
{
"bucket": "2023-12-18T00:00:00.000Z",
"all": 58,
"active": 79,
"new": 1,
"alumni": 0
}
]
```
Related to: https://github.com/open-sauced/engineering/issues/217
1. Run API locally
2. Hit the contrib endpoint with a list:
```sh
'http://localhost:3003/v2/lists/455a7b96-07fc-44ee-a44c-a3fc021155d2/stats/contributions-evolution-by-contributor-t …
```

feat: v2 API 👨🏻‍🍳 - contributions-evolution-by-contributor-type

---

src/workspace/workspace.service.ts

This fixes using a left join select in getting all workspaces (which will select inclusively all workspaces, regardless of workspace membership)
Instead, we select for an inner join on the workspace memberships which excludes workspaces in membership 
Closes: https://github.com/open-sauced/api/issues/493
Related to: https://github.com/open-sauced/app/pull/2461#issuecomment-1896291984
1. Run API and hit GET `workspaces`
2. Note only workspaces that you belong to
```json5
{
"data": [
{
"id": "b7ac8426-0e45-4dd1-b5ae-a3bad012b6cc",
"created_at": "2024-01-17T15:25:34.557Z",
"updated_at": "2024-01-17T15:25:34.557Z",
"name": "yoyo",
"description": "yoyoyoyoyo",
"members": []
},
{
"id": "248d7cbe-df52-442b-b1c1-a4304cf1c995",
"created_at": "2024-01-05T16:23:51.003Z", …
```

fix: Inner join instead of left join select for getting all workspaces

---

src/insight/dtos/insight.dto.ts
src/insight/entities/insight.entity.ts
src/insight/insight-repo.service.ts
src/insight/insight.controller.ts
src/insight/insights.service.ts
src/insight/user-insight.controller.ts

- Adds `/v1/insights/{insightId}/repos` to get repositories for an insight page
- Adds flag to only return minimal data for an insight page. `?include=none`
Currently, the `v1/insights/{id}` endpoint also fetches repositories and members as part of its data. When fetching an insight that includes a large number of repositories like a CNCF dashboard https://app.opensauced.pizza/pages/bdougie/43/dashboard, fetching all the repositories causes a timeout. 
Fetching minimal insight information and repositories separately improves performance for UI applications.
```json
[
{
"id": 72,
"insight_id": 5,
"repo_id": 501028599,
"full_name": "open-sauced/insights",
"created_at": "2022-12-16T22:20:46.531Z",
"deleted_at": null
},
{
"id": 584,
"insight_id": 5,
"repo_id": 588205706,
"full_name": …
```

feat: add endpoint to fetch minimal insight and repositories

---

src/repo/repo.service.ts

This is a small fix that adds the overlooked active PR count for the returned repo stats
Closes: https://github.com/open-sauced/api/issues/500
Call the `v2/repos/search` and see returned stat data:
```
"pr_active_count": 12,
"open_prs_count": 7,
"merged_prs_count": 28,
"spam_prs_count": 0,
"draft_prs_count": 5,
"closed_prs_count": 12,
"pr_velocity_count": 8
```
👍🏼

fix: v2 API - Add missing active_prs count for repos

---

src/histogram/dtos/base.ts
src/pull-requests/pull-request.controller.ts
src/timescale/fork_github_events.service.ts
src/timescale/issue_comment_github_events.service.ts
src/timescale/issue_github_events.service.ts
src/timescale/pull_request_github_events.service.ts
src/timescale/pull_request_review_github_events.service.ts
src/timescale/push_github_events.service.ts
src/timescale/watch_github_events.service.ts

- Makes `repo` optional on the histogram dto: additionally, checks for at least one given filter being present before generating historgram
- Removes the `prs/list` endpoint
Closes https://github.com/open-sauced/api/issues/496
Closes https://github.com/open-sauced/api/issues/497
Hitting the pull request histogram endpoint without any filters results in expected bad request:
```json
{
"statusCode": 400,
"message": "Repo Ids cannot be empty",
"error": "Bad Request"
}
```
Adding a filter back (like `repo` or `contributor`) works

feat: v2 API - Make "repo" optional in histogram dtos

---

src/repo/repo.service.ts

This removes a hanging, broken base query builder that was trying to left join on `contributors` which did not exist:
```
[Nest] 37263  - 01/22/2024, 12:00:14 PM   ERROR [ExceptionsHandler] Relation with property path contributions in entity was not found.
TypeORMError: Relation with property path contributions in entity was not found.
at RelationCountAttribute.get relation [as relation] (/Users/jpmcb/workspace/opensauced/api/src/query-builder/relation-count/RelationCountAttribute.ts:106:19)
at SelectQueryBuilder.loadRelationCountAndMap (/Users/jpmcb/workspace/opensauced/api/src/query-builder/SelectQueryBuilder.ts:1099:36)
at RepoService.baseQueryBuilder (/Users/jpmcb/workspace/opensauced/api/src/repo/repo.service.ts:49:8)
at RepoService.findOneByOwnerAndRepo …
```

fix: v2 API - Removes a broken left join for "contributors" in repo base query builder

---

src/pull-requests/dtos/pull-request-page-options.dto.ts
src/timescale/pull_request_github_events.service.ts

Adds a `distinctAuthors` field (true or false) for PR searches. This forces the cte builder to partition by pr author instead of pr number in the given repo.
Closes: https://github.com/open-sauced/engineering/issues/226
Running this locally, hitting `prs/search`, and comparing the two results, notice that when `distinctAuthors` is true, there are no duplicate authors.

feat: v2 API - Add a "distinctAuthors" field for PR search DTO

---

src/contributor/contributor-insights.controller.ts
src/contributor/contributor.controller.ts
src/pull-requests/dtos/pull-request-contributor-insights.dto.ts
src/timescale/pull_request_github_events.service.ts

This PR refactors the services used by `contributors/` endpoints:
- `contributor/insights` now use the pull request contributor insight DTO
- This removes unnecessary filtering on `contributor/insights` endpoints that was not in the original v1 functionality.
- "repos" are now required when searching contributors via type (new, alumni, etc.)
- Adds a guard for requiring some filtering when doing `contributors/search`
Closes: https://github.com/open-sauced/api/issues/502
Related to: https://github.com/open-sauced/app/issues/2509
Run API locally and able to hit `contributors/search` and `contributors/insights/new`

feat: v2 API - Refactor contributor search

---

src/repo/repo.service.ts
src/workspace/dtos/create-workspace.dto.ts
src/workspace/workspace.service.ts

- Adds a `repos` payload to the workspaces creation workflow
- This also wraps the entire workspace creation flow in a transaction so it should rollback any changes when there's an error (like I saw with https://github.com/open-sauced/api/issues/511)
Closes: https://github.com/open-sauced/api/issues/509
Related to: https://github.com/open-sauced/app/pull/2502
Creating a workspace with:
```sh
curl -X 'POST' \
'http://localhost:3003/v1/workspaces' \
-H 'Authorization: Bearer <redacted>' \
-H 'Content-Type: application/json' \
-d '{
"name": "Test workspace 1",
"description": "A test workspace",
"members": [
{
"id": 12345,
"role": "owner"
},
{
"id": 42211,
"role": "viewer"
}
],
"repos": [
{
"full_name": "open-sauced/app"
},
{
"full_name": "open-sauced/api"
}
] …
```

feat: Workspace creation has "repos" payload

---

src/workspace/workspace.service.ts

- fix: Remove misplaced API injection
- fix: Left join now returns all members
N/a - hotfix for #512 which was causing 500s on fetching all repos
👍🏼 
Run locally and hit `GET workspaces/`: note the correct workspaces are returned and all members are returned.

fix: Remove misplaced API injection

---

migrations/20240122172009_rm_pr_reviews.sql

This is a followup to: https://github.com/open-sauced/api/pull/504 which removed PR review table entities and services but had missed this file for actually removing the table in the database.
Followup to: https://github.com/open-sauced/api/pull/504

fix: Add migration to remove PR reviews table

---

swagger.yaml

Quick followup to the v2 API fast forward in #517 - this updates the `swagger.yaml` doc to have the latest changes for `beta`
Related to:
- https://github.com/open-sauced/go-api/issues/6
- https://github.com/open-sauced/pizza-cli/issues/72
N/a - ran `npm run generate:swagger`

feat: V2 API swagger doc

---

src/user-lists/user-list-events-stats.service.ts
src/user-lists/user-list-stats.controller.ts

This is PR does a few things to fix the extremely inefficient `most-active-contributors` endpoint on the user lists stats service (which was causing general app slowdown and tablelocks for big lists):
- Removes sub-queries in favor of sole CTE expressions
- Counts total contributions from already returned entities (instead of making another call)
- Removes usage of subqueries in aggregating active/new/alum contributors in favor of filtering on the `users` common table expression
Run API locally with connection to timescale. Enter a list ID in the swagger frontend. Note speed of returned data:

fix: Fixup most active contributors call

---

src/repo/entities/repo_contributors.entity.ts
src/repo/repo.controller.ts
src/repo/repo.service.ts
src/timescale/repo-devstats.service.ts
swagger.yaml

This re-introduces a repo contributors stats endpoint that was accidentally removed during the v2 API transition. This wasn't used in the app, but was used in the CLI and may be brought into repo stats pages in the app at some point.
This also brings the swagger doc up to speed for the Go CLI client library
Fixes: https://github.com/open-sauced/api/issues/519
1. Run API locally
2. Hit the `repos/owner/repo/contributors` endpoint
3. See results:
```json5
{
"data": [
{
"login": "abdul-irfan-k",
"commits": 0,
"prs_created": 1,
"prs_reviewed": 0,
"issues_created": 0,
"commit_comments": 0,
"total_contributions": 1
},
// ... redacted
{
"commits": 0,
"prs_created": 7,
"prs_reviewed": 51,
"issues_created": 14,
"commit_comments": 0,
"total_contributions": 72
},
{
"login": …
```

fix: Re-introduces repo contributor stats endpoint

---

src/user-lists/user-list.controller.ts
src/user-lists/user-list.service.ts

In the case that a username is not provided to this function, we now query the user table to get the username given the user id.
Also fixes a swagger bug where the `DELETE` route for user list contributors expected an integer (and not the correct type, a string)
Related to a discussion here: https://github.com/open-sauced/api/pull/538#pullrequestreview-1860414985
Before (note that no `username` is populated - very sad!)
After (note that a `username` is populated - great!)
1. Run the API locally connected to an open sauced postgres
2. Hit the `POST v2/lists/:id/contributors` endpoint with an ID for a user
3. Note the `username` for that user is now returned

fix: get usernames for contributors posting to user list

---

src/repo/repo.controller.ts
swagger.yaml

This is a hotfix ontop of #537 which adds the missing paginated response decorator - this is needed for the CLI to get back into a good state: https://github.com/open-sauced/pizza-cli/pull/73
hotfix followup to #537

fix: Update missing paginated response for repos/owner/repo/contributors

---

src/user-lists/entities/user-list-contributor.entity.ts

- Adds the `login` field back to the user list contributor entity as needed for the UI. We left join on the users table, and the login is empty if the user_id is not in our data, which would fallback to the `username`.
BEFORE:
AFTER:

fix: add login to user list contributor data

---

src/repo/repo.service.ts

- Normalizes the repository name when querying a repository by name
- This should resolve the errors with repos not being found in https://github.com/open-sauced/app/pull/2608
1. Visit https://beta.api.opensauced.pizza/#/Repository%20service/findOneByOwnerAndRepo and search for `TanStack` `Router`
2. Note the 404 return
3. Run the API from this PR locally
4. Visit http://localhost:3001/#/Repository%20service/findOneByOwnerAndRepo and search for `TanStack` `Router`
5. Note the repo is returned with a 200 response

fix: normalize repo full_name when querying for individual repo

---

.env.example
src/app.module.ts
src/auth/auth.controller.ts
src/config/github.config.ts
src/config/index.ts
src/coupon/coupon.service.ts
src/user/dtos/apply-developer-pack.dto.ts

- Adds an endpoint to verify developer pack eligibility
Related to https://github.com/open-sauced/engineering/issues/58

feat: add API endpoint to verify developer package eligibility

---

src/timescale/repo-devstats.service.ts
src/user-lists/user-list-events-stats.service.ts

This PR fixes missing time ranges on the users CTE in a few spots: this CTE is used to aggregate a list of users for building stats in lists / workspaces.
This also fixes missing pagination offsets for those queries.
Closes: https://github.com/open-sauced/api/issues/554
1. Run API locally with DB / Timescale attached
2. Hit the most active contributors list endpoint with a list of many users
3. Data returns:

feat: Set a time range on user CTE queries to prevent full table scans

---

src/workspace/dtos/update-workspace-contributors.dto.ts
src/workspace/workspace-contributors.controller.ts
src/workspace/workspace-contributors.service.ts

cc @zeucapua 
---
This allows workspace contributors to be added via the post routes with their login.
Note: this allows for _either or_ to be the item that denotes adding the user. If the id is provided, that will take precedence over the login string.
Also note: in order to make posting with both a contributor id and a contributor login, I added prefixes on the two post routes:
- `/v2/workspaces/{id}/contributors/login/{contributorLogin}`
- `/v2/workspaces/{id}/contributors/id/{contributorId}`
Closes: #556 
Running locally, I'm able to add a user via the `login` body parameter:

feat: Allow for workspace contributors to be added by login

---

src/workspace/dtos/delete-workspace-contributors.dto.ts
src/workspace/workspace-contributors.controller.ts
src/workspace/workspace-contributors.service.ts

cc @zeucapua 
---
Followup to #559 
Adds ability to delete multiple workspace contributors in the delete route:
- Delete `/v2/workspaces/{id}/contributors` can take multiple user objects where either or user id or login is allowed
- Split the delete routes into:
- `/v2/workspaces/{id}/contributors/login/{contributorLogin}`
- `/v2/workspaces/{id}/contributors/id/{contributorId}`
Followup to / related to #559 
Delete now works to delete multiple workspace contributors. Also works to delete sole contributors based on login:

feat: Delete workspace contributors by login

---

src/user-lists/dtos/collaborators.dto.ts
src/user-lists/user-list.controller.ts

- Fixes issue where adding contributors to an existing list fails when only providing userIds
- Related to https://opensaucedworkspace.slack.com/archives/C0673JTK9JT/p1707859913659469

fix: accept array of id,login when adding list contributors

---

dev/apply-migrations.sh
migrations/20240212120131_personal_workspaces.sql
migrations/20240212120132_workspace_user_lists.sql
migrations/20240212120133_personal_workspace_backfill.sql
migrations/20240212120134_personal_workspace_insights_migrations.sql
migrations/20240212120135_personal_workspace_user_lists_migrations.sql
src/app.module.ts
src/insight/insights.module.ts
src/insight/insights.service.ts
src/insight/user-insight.controller.ts
src/pull-requests/pull-request.module.ts
src/timescale/timescale.module.ts
src/user-lists/entities/user-list.entity.ts
src/user-lists/user-list.controller.ts
src/user-lists/user-list.module.ts
src/user-lists/user-list.service.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user-personal-workspace.controller.ts
src/user/user.entity.ts
src/user/user.module.ts
src/workspace/entities/workspace-user-list.entity.ts
src/workspace/entities/workspace.entity.ts
src/workspace/workspace-insights.controller.ts
src/workspace/workspace-insights.service.ts
src/workspace/workspace-user-lists.controller.ts
src/workspace/workspace-user-lists.service.ts
src/workspace/workspace.module.ts
src/workspace/workspace.service.ts

- Migrations for:
- User lists glue table (very similar to insight pages)
- adding personal workspaces
- moving insight pages to personal workspaces
- moving user lists to workspaces
- Query for `user/personal-workspace` for the auth'd user
- Get / post / delete for workspace lists
- Get / post / delete for workspace user lists
- Updated post / delete for insights and userlists to work with personal workspaces
Closes #510

feat: initial personal workspace feature

---

src/auth/auth.controller.ts
src/auth/dtos/supabase-auth-response.dto.ts

Now that personal workspaces have been merged into the API, the `personal_workspace_id` property was missing from the SupabaseAuthDto. This PR adds it.
```
❯ curl -X 'GET' \
'https://beta.api.opensauced.pizza/v2/auth/session' \
-H 'Authorization: Bearer some-token'
{"id":"833231","user_name":"nickytonline","role":"authenticated","email":"nick@nickyt.co","confirmed_at":"2023-07-30T03:31:02.219611Z","last_sign_in_at":"2024-02-14T23:25:33.694218Z","created_at":"2023-07-30T03:31:02.215221Z","updated_at":"2024-02-14T23:25:33.695574Z","is_onboarded":true,"insights_role":50,"is_waitlisted":false,"name":"Nick Taylor","location":"Montreal, Canada","bio":"Senior Software Engineer at OpenSauced","twitter_username":"nickytonline","company":"@open-sauced","display_local_ …
```

fix: added the missing personal_workspace_id property to the SupabaseAuthDto

---

src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user.module.ts
src/workspace/dtos/create-workspace.dto.ts
src/workspace/dtos/update-workspace-contributors.dto.ts
src/workspace/workspace.service.ts

This patch supports a list of contributors for workspace creation.
Closes: https://github.com/open-sauced/api/issues/561
Related to: https://github.com/open-sauced/app/pull/2658
cc @zeucapua 
1. Run API locally attached to database
2. Create a new workspace with a body like:
```sh
curl -X 'POST' \
'http://localhost:3003/v2/workspaces' \
-H 'Authorization: Bearer <redacted>' \
-H 'Content-Type: application/json' \
-d '{
"name": "My Workspace",
"description": "A workspace for my OSS collaborators",
"members": [],
"repos": [
{
"full_name": "open-sauced/api"
}
],
"contributors": [
{
"login": "bdougie"
}
]
}'
```
and the workspace is successfully created with associated repo/contributor from list.

feat: Workspace creation supports contributors

---

migrations/20240214140131_users_accept_usage_terms.sql
src/auth/auth.controller.ts
src/user/services/user.service.ts
src/user/user.entity.ts

- Adds an endpoint to support accepting the OpenSauced usage terms for an authenticated user
Related to - https://github.com/open-sauced/engineering/issues/236
1. Run the API locally using a Bearer token
2. Hit the `/auth/profile/accept-usage-terms` endpoint with a `PATCH` request
3. Note user id is returned, and the `accepted_usage_terms` flag is set to `true`

feat: add endpoint to accept usage terms for users

---

migrations/20240215112913_user_fetch_error_column.sql
npm-shrinkwrap.json
package.json
src/config/github.config.ts
src/insight/dtos/create-insight.dto.ts
src/insight/insight-repo.service.ts
src/insight/insights.module.ts
src/insight/user-insight.controller.ts
src/repo/dtos/repo-info.dto.ts
src/repo/repo.module.ts
src/repo/repo.service.ts
src/user-lists/user-list.module.ts
src/user-lists/user-list.service.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/workspace/workspace-contributors.service.ts
src/workspace/workspace-repos.service.ts
src/workspace/workspace-user-lists.service.ts

This adds octokit (alongside a personal web token auth method) to fetch github users / repos when workspaces flows add unknown users/repos.
The biggest thing is that we need the user/repo ID: because we don't generate IDs as the primary key for either the user table nor the repo table, we get those directly from GitHub. So attempting to come up with a "temporary" or partial entry that can latter get picked up by the ETL is abit of a mess.
Instead, this uses the octokit directly and gets those entities and fills in the necessary partial entries to be filled in at a latter time by the ETL.
---
This also refactors the workspaces repos and contributors service functions to use a common "execute..." function that performs that functionality.
Closes: …

feat: Add octokit and fetching users/repos for workspaces flows

---

src/workspace/workspace.service.ts

Enforces that a user cannot delete their personal workspace.
Closes: https://github.com/open-sauced/api/issues/578
Attempting to delete my local DB personal workspace:

feat: User cannot delete their personal workspace

---

src/insight/insights.service.ts
src/user-lists/user-list.service.ts

- Adds the associated workspace to the individual insight and list data
- This is needed for redirects for existing insight pages and lists, which can be public and accessed without logging in

feat: add associated workspace to insight and list data

---

src/histogram/histogram.module.ts
src/histogram/top.controller.ts
src/timescale/common/repos.spec.ts
src/timescale/common/repos.ts
src/timescale/entities/watch_github_events_histogram.ts
src/timescale/pull_request_github_events.service.ts
src/timescale/watch_github_events.service.ts

This is a proof of concept to validate some ideas/thoughts in: https://github.com/open-sauced/api/issues/592
This creates a new controller / service that gets the top starred repos in a 1 day period. This same strategy could be applied to forks, pull requests, etc.
This PR also refactors the repo name sanitation function:
- forces the correct spelling of "sanitize" 😮‍💨 🙈 
- overloads the function to work with sole repos
---
We can merge this but I mostly just wanted to hack on something quick that could validate this approach / if it's the direction all the other events would go down.
Related to: https://github.com/open-sauced/api/issues/592 cc @bdougie

feat: Proof-of-concept - top watch events in last 1 day

---

src/user-lists/dtos/collaborators.dto.ts

This is a very small fixup for the example in the user list update DTO
and should really only affect the swagger frontend.
Related to: https://github.com/open-sauced/app/issues/2754

fix: Use correct example in user list contributors DTO

---

src/histogram/top.controller.ts
src/timescale/entities/fork_github_events_histogram.ts
src/timescale/entities/issue_comment_github_events_histogram.ts
src/timescale/entities/pull_request_review_comment_events_histogram.entity.ts
src/timescale/fork_github_events.service.ts
src/timescale/issue_comment_github_events.service.ts
src/timescale/timescale.module.ts
src/timescale/watch_github_events.service.ts

This implements:
- Top forked repos
- Top commented repos: this incorporates both issue comments and pr review comments
- Top _new_ starred repos: this filters down the top repo results down to only those that are newly created/newly made public
Closes: https://github.com/open-sauced/api/issues/592

feat: Implements top new starred repos, forks, and comments

---

src/stripe/stripe.service.ts

This allows for Stripe checkout sessions to accept ACH payments
At the checkout screen on Stripe's frontend, they dynamically determine which option is best for the given user (probably by checking if there's existing payment methods for that given customer): so there's no way to make ACH the default always since we're relying on Stripe's frontend mechanisms.
Closes https://github.com/open-sauced/engineering/issues/258
When we have bigger deals / subscription tiers, we can remove the `card` option from those checkout sessions.
1. Run API locally, run App locally (with some of Zeu's "Upgrade Workspace" changes, run stripe CLI locally listening for events to forward to the local webhook
2. Go through the "Upgrade Workspace" flow and see that bank account is now an option

feat: Stripe payments accept ACH

---

src/workspace/workspace.service.ts

This fixes an issue where workspace creation would not make repo stubs (and fail with 404s if there are repos we don't have yet in our database).
Closes: https://github.com/open-sauced/api/issues/603
Followup: https://github.com/open-sauced/api/pull/573
Can successfully create workspace with repo that does not exist in our data:
and it shows up in the data

feat: workspace creation calls "tryFindRepoOrMakeStub"

---

migrations/20240229104813_rename_personal_workspaces.sql
src/user/services/user.service.spec.ts
src/user/services/user.service.ts
src/user/user-personal-workspace.controller.ts

Updates copy for users who have not updated their personal workspace name.
Closes: https://github.com/open-sauced/api/issues/608
cc @isabensusan for copy approval
Ran migration on local copy of database and ran app locally 👍🏼

feat: Rename "Personal workspace" to "Your workspace"

---

src/workspace/dtos/move-workspace-insight.dto.ts
src/workspace/workspace-insights.controller.ts
src/workspace/workspace-insights.service.ts

Implements the ability to move workspace insights from one workspace to another.
Note: user moving workspace insight must be an editor or an owner of _both_ workspaces in order to move the insight.
Implements API changes needed for: https://github.com/open-sauced/app/issues/647
Moved an insight between 2 of my own workspaces:
and it shows up correctly after the move:

feat: Ability to move workspace insights

---

src/stripe/stripe.service.ts

Self explanatory: allows for the checkout session to have promo codes for pro workspaces.
This will be useful to have in the future but will also be nice for OpenSauced internal members to use in production.
Followup to: #576

feat: Allow for promo-codes in pro workspaces

---

src/repo/repo.service.ts

This is a quickfix for adding the missing repo-id to the error message for which repos are missing when adding them to an insights page
related to: https://github.com/open-sauced/app/issues/2814#issuecomment-1977520256

fix: Add repo ID for missing repo in error message

---

src/workspace/dtos/workspace-stats.dto.ts
src/workspace/workspace-stats.service.ts

Adds workspace stat filtering based on a provided list of repo names
Related to: https://github.com/open-sauced/app/issues/2581
Filtering on 2 repos:
Filtering on 3 repos:

feat: Add workspace stat filtering by repo name

---

src/repo/repo.service.ts
src/workspace/workspace-repos.controller.ts
src/workspace/workspace-repos.service.ts
src/workspace/workspace.module.ts

This implements a
```
GET v2/workspaces/UUID/repos/search
```
endpoint that reuses the repo service functionality for `v2/repos/search`.
Further, this refactors a few things in the repo service functionality to work with workspaces:
- a private `findAllWithFiltersScaffolding` function that takes an optionally undefined "workspaceId" which can be used to filter on a workspace ID.
- fixes the broken counter by using the CTE counter method (where we use the base query to count returned entities): this should actually be _abit_ faster since we're using a `COUNT(*)` directly instead of `count(repo_id)` which will actually query for the individual rows in that specific column.
Related to: https://github.com/open-sauced/app/issues/2581
Normal `v2/repos/serach` still works (note use of "topic" …

feat: Workspace repo search with filters

---

src/timescale/pull_request_github_events.service.ts

This fixes a bug where the pr stats were using a CTE that gets only the latest PR event for a given PR. This effectively made getting PR stats for _all_ events miss overlapping opened/closed events in a time period.
Fixes: https://github.com/open-sauced/app/issues/2872
Using the `v2/repos/search` endpoint:
```
"pr_active_count": 3,
"open_prs_count": 3,
"merged_prs_count": 5,
"spam_prs_count": 0,
"draft_prs_count": 0,
"closed_prs_count": 1,
"pr_velocity_count": 0,
"activity_ratio": 2.4924114971381774,
"health": 2.4924114971381774
```
```
"pr_active_count": 7,
"open_prs_count": 7,
"merged_prs_count": 5,
"spam_prs_count": 0,
"draft_prs_count": 0,
"closed_prs_count": 1,
"pr_velocity_count": 0,
"activity_ratio": 2.4924114971381774,
"health": 2.4924114971381774
```

fix: PR stats now get all pr events, not just most recent

---

src/workspace/workspace-members.controller.ts
src/workspace/workspace-members.service.ts

Allows for pass-through auth on the workspace members
Related to: https://github.com/open-sauced/app/pull/2879

feat: Allow for workspace member access GET of all users

---

src/workspace/dtos/move-workspace-list.dto.ts
src/workspace/workspace-user-lists.controller.ts
src/workspace/workspace-user-lists.service.ts

Implements moving a user list to a different workspace. Followup to: https://github.com/open-sauced/api/pull/613
Closes: https://github.com/open-sauced/api/issues/619
Moved this user list to a new workspace via that `v2/workspaces/{id}/userLists/{newWorkspaceId}`

feat: Implements moving a workspace user list

---

src/workspace/workspace-insights.service.ts
src/workspace/workspace-user-lists.service.ts

Quickfix to order repo and contributor lists by when they were last updated.
Closes: https://github.com/open-sauced/api/issues/629
QA'd locally: updated a repo insight and saw it show up at the top of the list. And did the same for a contrib list.

fix: Repo / contributor insights in workspace are ordered by when they were last updated

---

src/insight/insight-repo.service.ts
src/repo/repo.service.ts

Allows for stubbing out repos in the insights flow with _both_ a repo ID and repo org/name.
Fixes: https://github.com/open-sauced/app/issues/2814
Successfully added a repo to an insight page with the following patch info:

fix: Allow for stubbing out repos with repo ID and org/name

---

src/insight/user-insight.controller.ts
src/user-lists/dtos/update-user-list.dto.ts
src/user-lists/user-list.controller.ts
src/user-lists/user-list.service.ts
src/workspace/workspace-insights.controller.ts
src/workspace/workspace-insights.service.ts
src/workspace/workspace-user-lists.controller.ts
src/workspace/workspace-user-lists.service.ts

This allows for owners/editors to manage workspace insight pages correctly and not rely on individual entity membership to denote access.
- Denotes old insight / user list routes that are to be deprecated
- Adds routes for workspace insight / user list access controls
Related to:
- https://github.com/open-sauced/api/issues/634
- https://github.com/open-sauced/app/issues/2862
- https://github.com/open-sauced/app/pull/2901
See validations in comments below:

fix: Refactors access control for workspace insight pages

---

src/workspace/workspace-insights.service.ts
src/workspace/workspace-user-lists.service.ts

- Adds pagination options to endpoints for repository and contributor lists
Fixes https://github.com/open-sauced/app/issues/2873
1. Run API locally
2. Use contributor or repository lists for workspace with more than 10 of either
3. Make the request
4. Note only first 10 are returned by default

fix: apply pagination to repository/contributor insights lists

---

src/workspace/workspace-contributors.service.ts
src/workspace/workspace-members.service.ts
src/workspace/workspace-orgs.service.ts
src/workspace/workspace-repos.service.ts
src/workspace/workspace.service.ts

Fixes pagination for the `GET` routes on the various workspaces endpoints
Closes https://github.com/open-sauced/api/issues/643
and is related to https://github.com/open-sauced/app/pull/2939

fix: Makes pagination work for get workspaces routes

---

src/workspace/workspace-stats.service.ts

This is a small fix to get the individual bucket data from the histograms being used to calculate workspace stats (stars & forks).
Closes: https://github.com/open-sauced/app/issues/2953
Using the `daytonaio/daytona` repo:

fix: Tease out buckets of data for workspace stats

---

src/repo/entities/repo.entity.ts
src/repo/repo.service.ts
src/timescale/entities/fork_github_events.ts
src/timescale/entities/watch_github_events.ts
src/timescale/repo-devstats.service.ts
src/timescale/timescale.module.ts
src/user/services/user.service.spec.ts

This implements a proof of concept scaffolding for the "Contributor Confidence" rating
See in code comments for metric explanation.
CC @bdougie - I modified the algorithm _slightly_ from when we last touched base: now, forks are a weight of `0.5` and stars are a weight of `0.1`: this way, scores never surpass `100%`. I'd imagine, in the future, contributions directly to a project (like making an issue, PR, etc.) would be a weight of `1` to the score.
Related to (and first step in): https://github.com/open-sauced/api/issues/588
1. Call `v2/repos/search` on a given repo
2. Notice confidence score:
for example, here's the score for `open-sauced/app`:
```
"contributor_confidence": 0.16980519480519482,
```
or more plainly, 16% chance/confidence that a fly by contribution will turn into a …

feat: Implements POC contributor confidence

---

migrations/20240320113501_remove_pull_req_table.sql

Since we get this data from Timescale now, we can remove this table and clean up _alot_ of space in our DB.
Related to: https://github.com/open-sauced/etl/pull/174

chore: Remove pr table from first party db

---

src/common/filters/repo-filter.service.ts
src/repo/repo.service.ts
src/timescale/pull_request_github_events.service.ts
src/user/services/user.service.spec.ts
src/user/services/user.service.ts

Removes hanging references to the `pull_requests` table that is being refactored out.
Followup to:
- #674 
- #671

chore: Removes hanging "pull_requests" table references in raw strings

---

src/histogram/dtos/base.dto.ts
src/timescale/commit_comment_github_events.service.ts
src/timescale/create_github_events.service.ts
src/timescale/delete_github_events.service.ts
src/timescale/fork_github_events.service.ts
src/timescale/gollum_github_events.service.ts
src/timescale/issue_comment_github_events.service.ts
src/timescale/issues_github_events.service.ts
src/timescale/member_github_events.service.ts
src/timescale/pull_request_github_events.service.ts
src/timescale/pull_request_review_comment_github_events.service.ts
src/timescale/pull_request_review_github_events.service.ts
src/timescale/push_github_events.service.ts
src/timescale/release_github_events.service.ts
src/timescale/watch_github_events.service.ts

There are a few places (mostly the workspace stats functionality) the "genHisto" functions get called _outside_ of the NestJS operations (which then don't fill in the defaults from the decorators).
Closes: https://github.com/open-sauced/api/issues/682
Followup fix to: #681 
Workspace stats endpoint now working:

fix: Adds checks for optional base-histo dto fields

---

src/repo/entities/repo.entity.ts
src/repo/repo.service.ts
src/user/services/user.service.spec.ts

Adds fork velocity to repos entity. For example, on the OpenSauced App repo:
```
"fork_velocity": 0.4,
```
there's about 1 fork every 2-3 days or so. This is taken by an aggregate average of the forks histogram over the provided range.
Closes: #666 
Using the `open-sauced/app` repo in the `v2/repos/search`:
```sh
'http://localhost:3003/v2/repos/search?page=1&limit=10&range=30&prev_days_start_date=0&repo=open-sauced%2Fapp' \
```
this returns:
```json5
{
"data": [
{
"id": 501028599,
// etc. etc.
"pr_velocity_count": 1,
"fork_velocity": 0.4,
}
],
"meta": {
"page": 1,
"limit": 10,
"itemCount": 1,
"hasNextPage": false
}
}
```

feat: Adds fork velocity to repos entity

---

src/star-search/star-search.service.ts

Annotates usernames in the star search response with "@" like `@jpmcb`.
N/a - related to ongoing star-search work. cc @nickytonline 
Example prompt from the star-search endpoint:
```
Based on the provided GitHub activities and contributions data, there is one user who has made
a pull request that addresses Firefox functionality in the freeCodeCamp repository.**User Login Information**:
The user is identified as @moT01.**Repository Details**: The repository in question is
freeCodeCamp/freeCodeCamp, although the repository name was not explicitly provided in
the initial data.
```

feat: Prompt engineering - annotate usernames with "@"

---

src/repo/repo.service.ts

feat: add devstats to owner/repo endpoint

---

src/timescale/pull_request_github_events.service.ts
src/user/dtos/user-prs.dto.ts

Now, the `v2/users/username/prs` endpoint can take an optional `repoIds` param to filter on the repo IDs (instead of / alongside the repo name). This should be a comma delimited string of the repo IDs like so:
```
499330806,499330999
```
Closes: #788 
1. Call the endpoint with a list of repo ids like so:
```sh
'http://localhost:3003/v2/users/jpmcb/prs?page=1&limit=10&range=30&prev_days_start_date=0&repoIds=499330806,501028599' \
```
2. Witness the results
```json5
{
"data": [
{
"event_id": 38334045471,
"pr_number": 789,
"pr_state": "open",
"pr_is_draft": false,
"pr_is_merged": false,
"pr_mergeable_state": "unknown",
"pr_is_rebaseable": false,
"pr_title": "feat: Upgrade to GPT-4o",
"pr_head_label": "jpmcb:gpt-4o",
"pr_base_label": …
```

feat: v2/users/username/prs now supports repoIds
