open-sauced/api

.envrc, src/app.module.ts, src/config/stripe.config.ts, src/customer/customer.service.ts, src/main.ts, src/stripe-webhook/stripe-webhook.controller.ts, src/stripe-webhook/utils.ts, src/stripe-webhook/webhook.module.ts, src/stripe/stripe.service.ts, src/subscription/stripe-subscription.dto.ts, src/subscription/stripe-subscription.module.ts, src/subscription/stripe-subscription.service.ts, src/user/user.service.ts, supabase/migrations/20221221124600_add_customers.sql, supabase/migrations/20221221124800_add_subscriptions.sql
This PR:
- Adds a `stripe/webhooks` endpoint to listen for Stripe webhooks
- Adds the `STRIPE_WEBHOOK_SECRET` to the `.envrc` template
- Adds an entity for managing subscriptions
=> feat: add stripe webhook integration for subscriptions

src/contributor/contributor-insights.controller.ts, src/contributor/contributor.module.ts, src/pull-requests/pull-request.service.ts
- Gathers new contributors from "days" range, using `PullRequestContributorOptionsDto`, who did not contribute in previous days range based on pull request activity.
- Can provide a number of repo ids to support many repos within a insights dashboard.
- Creates new `/contributors/insights/` controller
Related to some discussion in the Insights repo and during team discussions.
N/a
Running the query with the date/time ranges of 0-30 days inclusive and 30-60 exclusive results in rows of contributors on repos who have not contributed in the exclusive range:
```bash
'http://localhost:3001/v1/contributors/insights/new?page=1&limit=10&range=30&topic=javascript&repoIds=501028599' \
```
Note that `501028599` is the id of the dev database's …
=> feat: add new API endpoint for contributor insights

.eslintrc.js, src/highlight/highlight.controller.ts, src/user/user-highlights.service.ts
Adds and endpoint to list top highlights for the given day range (7 days) be default
https://github.com/open-sauced/ops-backend/issues/87
Sample output
```json
{
"data": [
{
"id": 169,
"user_id": 47471007,
"url": "https://github.com/open-sauced/ai/pull/211",
"title": "feat: make formal the default tone",
"highlight": "test",
"type": "pull_request",
"pinned": false,
"featured": false,
"created_at": "2023-07-31T17:11:22.330Z",
"updated_at": "2023-07-31T17:11:22.330Z",
"shipped_at": "2023-07-31T22:11:22.277Z"
},
{
"id": 170,
"user_id": 42211,
"url": "https://github.com/brandonroberts/blog/pull/39",
"title": "Test unknown repo from highlight",
"highlight": "I wrote a blog post",
"type": "pull_request",
"pinned": false,
"featured": false,
"created_at": …
```
=> feat: add endpoint to list top highlights for the date range

src/contributor/contributor-insights.controller.ts, src/pull-requests/pull-request.service.ts
- Adds endpoints for repeat and churned contributors for the provided repo IDs.
- Also fixes a bug for the contributor insights for new contributors
Related to https://github.com/open-sauced/ops-backend/issues/6
Churn contributors for `open-sauced/insights` based on development data
```json
{
"data": [
{
"author_login": "ThePromiseBenard"
}
],
"meta": {
"page": 1,
"limit": 10,
"itemCount": 1,
"hasNextPage": false
}
}
```
Repeat contributors for `open-sauced/insights` based on development data
```json
{
"data": [
{
"author_login": "babblebey"
},
{
"author_login": "brandonroberts"
},
{
"author_login": "foxyblocks"
},
{
"author_login": "Lucif3r-in"
},
{
"author_login": "OgDev-01"
}
],
"meta": {
"page": 1,
"limit": 10,
"itemCount": 5, …
```
=> feat: add endpoints for churned and repeat contributors

src/pizza/dtos/baked-repo.dto.ts, swagger.yaml
API calls to [POST /v1/bake](https://api.opensauced.pizza/#/Pizza%20oven%20service/Bake%20a%20repository%20with%20the%20pizza%20oven%20microservice) fail with status code 400 because the expected type in the pizza service is boolean.
Relates to https://github.com/open-sauced/go-api/issues/2
1. Go to https://api.opensauced.pizza/#/Pizza%20oven%20service/Bake%20a%20repository%20with%20the%20pizza%20oven%20microservice
2. Set environment to production
3. Set the request body to:
```
{
"url": "https://github.com/open-sauced/insights",
"wait": "false"
}
```
4. Observe the response status code to be 400
5. Set the request body to:
```
{
"url": "https://github.com/open-sauced/insights",
"wait": false
}
```
6. Observe the response status code to be 201
N/A
Update / regenerate the …
=> fix: update BakeRepoDto.wait to boolean

src/highlight/dtos/highlight-options.dto.ts, swagger.yaml
The highlights usernames that are returned in the array are of type "string" for the individual items for the swagger doc.
N/a - related to ongoing swagger Go API client generation shenanigans.
N/a
=> fix: Highlight users string type in array for swagger

README.md, src/pull-requests/entities/pull-request-insight.entity.ts, swagger.yaml
This PR fixes the incorrect property type for `pull-request-insight` entity.
The `day` property was originally set to type `date-time` which is not a valid type.
To fix this, the property's type had to be set to `string` with format `date`.
Relates to https://github.com/open-sauced/go-api/issues/3
Please, release a new minor version from the beta branch, including these changes.
They will then be consumed by the [open-sauced/go-api](https://github.com/open-sauced/go-api) where a new release will also be needed.
=> fix: incorrect property type for pull-request-insight entity

src/common/dtos/page-options.dto.ts, src/common/filters/repo-filter.service.ts, src/common/util/datetimes.ts, src/pull-requests/pull-request-insights.service.ts, src/pull-requests/pull-request.service.ts, src/repo/repo.service.ts, src/user/user-highlights.service.ts
This allows for more dynamic timeblocks for contributor insights. I.e., set the "start" date for when churn, new, etc. contributors are determined. This introduces the `prev_days_start_date` param which are the number of days to go back to in order to start the range block. The default is `0` which maintains the current behavior of using `now()` blocks in the sql. 
Here's an example that uses `user/prs` where `0` days are used as the previous day start date:
```sh
'http://localhost:3003/v1/users/jpmcb/prs?page=1&limit=10&range=30&prev_days_start_date=0' \
```
```json5
{
"data": [
{
"id": 1520390100,
"repo_id": 499330806,
"number": 312,
"state": "OPEN",
"draft": true,
"merged": false,
"mergeable": false,
"rebaseable": false,
"title": "feat: …
```
=> feat: Dynamic API timeblocks for queries with ranges

src/user-lists/dtos/contributions-timeframe.dto.ts, src/user-lists/dtos/most-active-contributors.dto.ts, src/user-lists/entities/contributions-projects.entity.ts, src/user-lists/entities/contributions-timeframe.entity.ts, src/user-lists/entities/contributors-timeframe.entity.ts, src/user-lists/entities/user-list-contributor-stats.entity.ts, src/user-lists/user-list-stat.service.ts, src/user-lists/user-list-stats.controller.ts, src/user-lists/user-list.module.ts
Implements the `list/:id/stats` endpoints - currently a WIP
```sh
'http://localhost:3003/v1/lists/<list-id>/stats/most-active-contributors?page=1&limit=10&range=30&contributorType=all' \
```
```json5
{
"data": [
{
"commits": 193,
"prsCreated": 46
},
{
"commits": 26,
"prsCreated": 23
}
],
"meta": {
"page": 1,
"limit": 10,
"itemCount": 2,
"hasNextPage": false
}
}
```
This is a list I made with me and @brandonroberts on it. This route also supports
- `contributorType`:
- `all` (everyone)
- `active` (have contributed in the last 2 time date ranges)
- `alumni` (have not contributed in the last time date range but did in the …
=> feat: Initial `lists/:id/stats` features

src/user-lists/entities/user-list.entity.ts, src/user-lists/user-list.controller.ts, src/user-lists/user-list.service.ts
This PR is twofold:
- Surfaces the `user_id` when querying for a list via `GET list/:id`. This column previously was not selected
- Makes it so anyone can get a public list. Before, the `findOneById` the controller used would always only select lists that matched the `user_id` of the authenticated user.
Example of getting a public list for an authenticated user:
```
'http://localhost:3003/v1/lists/408a7817-87ad-4ec6-bd87-3c5c1687c05f' \
{
"id": "408a7817-87ad-4ec6-bd87-3c5c1687c05f",
"user_id": 23109390,
"name": "Woof",
"is_public": true,
"created_at": "2023-09-19T03:28:49.609Z",
"updated_at": "2023-09-19T03:28:49.609Z",
"deleted_at": null
}
```
Example of getting an auth error for a non public list:
``` …
```
=> feat: `GET /list/:id` able to be public for authenticated users

src/user-lists/user-list-stat.service.ts
Fixes `commits` returned from the user list stats endpoints potentially having `null` as a value. This ensures that null values are 0 for user commit data.
```json
{
"data": [
{
"login": "0-vortex",
"commits": null,
"prs_created": 0
},
{
"login": "nickytonline",
"commits": 292,
"prs_created": 21
},
{
"commits": 275,
"prs_created": 44
},
{
"login": "OgDev-01",
"commits": 184,
"prs_created": 15
},
{
"login": "BekahHW",
"commits": 52,
"prs_created": 11
},
{
"commits": 26,
"prs_created": 15
},
{
"login": "bdougie",
"commits": 15,
"prs_created": 4
},
{
"login": "isabensusan",
"commits": 11,
"prs_created": 1
}
],
"meta": {
"page": 1,
"limit": 10,
"itemCount": 8,
"hasNextPage": false
}
}
```
```json
{
"data": …
```
=> fix: Coalesce on commits in list stats

src/user-lists/user-list-stat.service.ts
Followup to #352 
Fixes ordering not landing in derived field for `total_contributions` which happens after the CTE executes.
Related to https://github.com/open-sauced/app/pull/1796/commits/32bc78a536124727bbc0a6fe4e97367c69bb287f![]
=> fix: Ordering for CTE based query

src/common/filters/repo-filter.service.ts, src/pull-requests/pull-request-insights.service.ts, src/pull-requests/pull-request.service.ts, src/repo/repo.service.ts, src/user-lists/user-list-stat.service.ts, src/user/user-highlights.service.ts
Throughout our psql calls, we had been using `::DATE` casts to filter queries based on sliding time windows.
These would truncate down ISO timestamps to remove the "time" precision from the date/time strings, leaving essentially just the date. However, when compared to _other_ timestamps we carry data for, we essentially re-cast the date to a timestamp with empty "time".
For example, when getting pull requests for a contributor:
https://github.com/open-sauced/api/blob/84a0e3c01be9d1bef36e219a9b66f265419478d0/src/pull-requests/pull-request.service.ts#L83
given the "startDate" is "NOW()", this would truncate the date ISO string down to something like `2023-10-05` DATE. This is equivalent to the timestamp `2023-10-05 00:00:00Z` which, when compared to _other_ timestamps within the current …
=> fix: Refactors `::DATE` casts to `::TIMESTAMP` casting

src/user-lists/user-list-stat.service.ts
This returns empty results (instead of 404) for lists that do not have contributors within certain filtered categories.
```json
{
"data": [],
"meta": {
"page": 1,
"limit": 10,
"itemCount": 0,
"pageCount": 0,
"hasNextPage": false,
"allContributionsCount": 0
}
}
```
This also fixes an issue where there would be "null" returned for time-series chunks that don't have stats for a certain time frame. Now, `0` is returned instead.
```json
[
{
"commits": 0,
"prs_created": 0,
"time_start": "2023-09-11T16:01:59.857Z",
"time_end": "2023-09-15T22:53:25.571Z"
},
{
"commits": 0,
"prs_created": 0,
"time_start": "2023-09-15T22:53:25.571Z",
"time_end": "2023-09-20T05:44:51.285Z"
},
{
"commits": 0,
"prs_created": 0,
"time_start": "2023-09-20T05:44:51.285Z",
"time_end": …
```
=> fix: user-lists stats for not found entities returns empty results

src/insight/insight-repo.service.ts, src/insight/insights.service.ts
This catches failures when posting repos to the pizza oven service. There is some validation that the pizza service does to ensure repos are actually git repos. And in some cases, they aren't (like with https://github.com/tamagui/sponsors)
This prevents unhandled errors from causing new insight pages to completely fail (as we saw in https://github.com/open-sauced/app/issues/2188)
Fixes: https://github.com/open-sauced/app/issues/2188
and partially related to: https://github.com/open-sauced/pizza/issues/61
We can now sync the entire tamagui org without failure:
=> fix: try/catch for posting to pizza service

src/user-lists/user-list.controller.ts, src/user-lists/user-list.module.ts, src/user-lists/user-list.service.ts
Adds the `/:id/contributors/highlights` endpoint for user lists returning highlights. Here are some results from a list I have with Bekah on beta:
```json
{
"data": [
{
"id": 249,
"user_id": 34313413,
"url": "https://github.com/withastro/docs/pull/4829",
"title": "",
"highlight": "As I was going through the Astro documentation, I found a couple of links with broken paths. I read through the contributing guide and made the updates. Thanks, Astro docs for making it an easy contribution!",
"type": "pull_request",
"pinned": false,
"featured": false,
"created_at": "2023-11-03T18:26:08.452Z",
"updated_at": "2023-11-03T18:26:08.452Z",
"shipped_at": "2023-11-04T00:26:08.414Z",
"tagged_repos": [
"withastro/docs"
]
},
{
"id": 248,
"user_id": 34313413,
"url": …
```
=> feat: User highlights for users in list contributors

src/workspace/workspace.controller.ts, src/workspace/workspace.service.ts
This implements a "get" for a sole workspace:
Related to: https://github.com/open-sauced/engineering/issues/215
Related to: https://github.com/open-sauced/app/issues/2437
1. Using route while authenticated:
```sh
'http://localhost:3003/v1/workspaces/248d7cbe-df52-442b-b1c1-a4304cf1c995' \
```
yields the workspace json blob:
```json5
{
"id": "248d7cbe-df52-442b-b1c1-a4304cf1c995",
"created_at": "2024-01-05T23:23:51.003Z",
"updated_at": "2024-01-05T23:23:51.003Z",
"name": "My Workspace",
"description": "A workspace for my OSS collaborators",
"members": [
{
"id": "d0ef702a-2588-4b3f-9daf-0d822cdd52c4",
"user_id": 23109390,
"workspace_id": "248d7cbe-df52-442b-b1c1-a4304cf1c995", …
```
=> feat: "get" for single workspace

src/repo/entities/repo.entity.ts, src/repo/repo.service.ts
This removes the unused activity ratio from the repo entity: this should help keep the `v2/repos/search` hot path from getting too bogged down
N/a - followup to #523
=> fix: Removes activity ratio from repo entity

src/repo/entities/repo.entity.ts, src/repo/repo.service.ts, src/timescale/repo-devstats.service.ts, src/workspace/entities/workspace-stats.entity.ts, src/workspace/workspace-stats.service.ts
This PR does a few things:
- Reverts https://github.com/open-sauced/api/pull/526 which removed activity ratios for individual repos when we were triaging an incident.
- Adds a separate "health" and "activity_ratio" since eventually these will be different: the "health" stats will be informed by many things, not just activity ratio. 
- Makes the upper quantile `upperQ` variable `0.75` which ignores more repos that are extreme outliers for activity among all repos on github.
Related to: https://github.com/open-sauced/engineering/issues/246
and: https://github.com/open-sauced/api/issues/552
N/a
1. Run API locally
2. Hit the repos/search endpoint
3. Notice the new `activity_ratio` field
```sh
'http://localhost:3003/v2/repos/search?page=1&limit=10&range=30&prev_days_start_date=0 …
```
=> feat: Add activity ratio back 

src/timescale/common/repos.spec.ts, src/timescale/common/repos.ts, src/timescale/entities/ross_index_histogram.ts, src/timescale/pull_request_github_events.service.ts, src/workspace/entities/workspace-ross.entity.ts, src/workspace/workspace-stats.controller.ts, src/workspace/workspace-stats.service.ts
Implements a workspaces route that returns data for the workspace repos and their ross index over time (in 1 week increments) and the number of new/recurring/internal contributors within those same time frames.
In the future, we can use both `findRossContributorsByRepos` and `findRossIndexByRepos` on individual repos to get more fine grained stats on those sole repos. 
Note: this is widely based on explorations by @bdougie in https://github.com/open-sauced/engineering/issues/37 and will enable the internal/external contributors timeseries as visualized in https://github.com/open-sauced/api/issues/585
Closes: https://github.com/open-sauced/api/issues/585
1. Create a workspace with some tracked repos
2. Hit this endpoint via the api like:
```sh
$ curl -X 'GET' \ …
```
=> feat: Implements ross index/contributors

src/timescale/pull_request_github_events.service.ts, src/workspace/dtos/update-workspace.dto.ts, src/workspace/workspace.service.ts
This fixes the use of `IsBooleanString` in a few spots:
- Workspace update dto now accepts an optional `is_public` and that boolean gets interpreted dynamically to update the workspace
- The `distinctAuthors` pull request event bool is now interpreted correctly
N/a - follow up to: https://github.com/open-sauced/api/pull/576 and https://github.com/open-sauced/app/issues/2727
Able to patch a workspace with an optional `is_public` flag:
```sh
❯ curl -X 'PATCH' \
'http://localhost:3003/v2/workspaces/8d9f8ee1-b5dc-452c-b547-6cd2e375f1ec' \
-H 'Authorization: Bearer <redacted>' \
-H 'Content-Type: application/json' \
-d '{
"name": "My personal woof workspace",
"description": "A workspace for my personal OSS collaborators"
}'
```
```json …
```
=> fix: Add parsing of boolean strings

.github/workflows/auto-add-to-project.yml
This PR adds a github action that auto-adds issues opened in the /api repo to the [Team Dashboard](https://github.com/orgs/open-sauced/projects/25)
-
-
-
- [ X] 🙅 no documentation needed
-
-
=> chore: create auto-add-to-project.yml to auto add opened issues to the team dashboard

src/repo/repo.service.ts, src/workspace/workspace-repos.service.ts, src/workspace/workspace-stats.service.ts
This includes abit of a hack with TypeORM to disable the default `deleted_at IS NULL` check on the left join.
Credit: https://stackoverflow.com/questions/66117005/typeorm-left-joining-without-deletedat-is-null
Closes: https://github.com/open-sauced/api/issues/627
=> fix: Left join deleted repos in workspace-repos

src/workspace/workspace-user-lists.service.ts
Real quick followup to: #635 which refactored access control to workspace insight pages. This removes the last hanging `findOneById` from the list service which didn't encompass our newer workspace auth correctly.
Followup: #635
=> fix: use workspace-repo service for `findOneById`

src/workspace/workspace-user-lists.service.ts
Followup to #637:
- Refactors `findOneUserListByWorkspaceIdForUserIdUnguarded` function name for workspace-list-service to reflect using list ID and not the user id to find workspace contrib lists
Followup to #635 and #636
Able to patch contrib list:
=> chore: Refactors workspace list-service `findOneUserList...` function name

src/workspace/workspace-insights.service.ts, src/workspace/workspace-user-lists.service.ts
- Fixes an issue when using pagination where the cumulative total records returns gets truncated when using joins across tables.
- One repository insight may have 10 repositories and 10 member associated with it and even if you have 11 total insights, it may only show 1 because the repos/members count against the pagination
- Using skip/take instead of offset/limit resolves this issue when querying data so all insights rows are returned before doing the joins and relational entities
=> fix: use skip/take for pagination with nested data for insights

src/insight/dtos/create-insight.dto.ts, src/user-lists/dtos/create-user-list.dto.ts
Since insight assets access control was hoisted up to the workspace level, we  don't need API consumers to provide a "is_private" key.
Leaving the option in place since we may need that in the future and there's alot to unwind with how insights work and their "membership"
Closes: https://github.com/open-sauced/api/issues/686
Related to: https://github.com/open-sauced/app/issues/3049#issuecomment-2025220342
Able to patch a repo insight without that DTO key:
Able to patch a user list without that DTO key:
=> fix: Make "is_public" in insights dto optional

src/repo/common/lotto.spec.ts, src/repo/common/lotto.ts, src/repo/dtos/repo-search-options.dto.ts, src/repo/entities/lotto.entity.ts, src/repo/repo.controller.ts, src/repo/repo.service.ts, src/timescale/entities/contributor_counts.entity.ts, src/timescale/pull_request_github_events.service.ts
Implements the lottery factor: see inline comments in the `src/repo/common/lotto.ts` for implementation details on the algorithm implemented.
Creates the `v2/repo/lotto` endpoint that can be queried to get lottery factor details. These details are in the form:
```json5
{
"all_contribs": [
{
"contributor": "contributor-login",  // name of the contributor
"count": 99,                         // the number of contributions in range
"percent_of_total": 0.99,            // the percentage of total contributions
"lotto_factor": "very-high"          // their individual lotto factor
},
// etc. etc. - rest of the contributors within time range for given repos
// and their lotto factor
{
"contributor": "other-contributor-login",
"count": 1,
"percent_of_total": 0.01,
"lotto_factor": "low"
}
],
// The …
```
=> feat: Implements the lottery factor

src/insight/user-insight.controller.ts, src/workspace/workspace-insights.service.ts, src/workspace/workspace.service.ts
Small PR to bump builds:
- corrects usage of `||` operator in favor of `??`
- Removes unused pager service in workspaces
- Removes unnecessary check for required `name` and `repos` dto elements
N/a - bumps builds after failure in last release run
=> fix: Corrects linting warnings (and bump builds)

src/repo/repo.service.ts
Fixes where repos with case sensitive names (from the `full_name` field in our metadata database) wasn't getting lower-cased correctly by the lottery factor calling function.
Followup to https://github.com/open-sauced/api/pull/804
Previously for `microsoft/TypeScript`:
```json5
{
"all_contribs": [],
"all_lotto_factor": "very-high",
"grace_period_end": "2014-07-17T15:28:39.000Z"
}
```
Now:
```json5
{
"all_contribs": [
{
"contributor": "jakebailey",
"count": 19,
"percent_of_total": 0.17592592592592593,
"lotto_factor": "moderate"
},
// ... etc.
],
"all_lotto_factor": "moderate",
"grace_period_end": "2014-07-17T21:28:39.000Z"
}
```
Call the /v2/repos/lotto endpoint with a "case-sensitive" repo name like `microsoft/TypeScript`.
=> fix: Found repos for lottery factor have full_names correctly lower-cased
